### PR TITLE
docs(jina): fix broken links in contributing doc instructions

### PR DESCRIPTION
**Pull request by atibaup**

### CODE REVIEW

**Review by Yongxuanzhang — APPROVED** [review]
LGTM 👍  Thank you so much for your contribution! ❤️

**Comment by Yongxuanzhang** [comment]
Hi @atibaup, could you merge/rebase from master and push again?

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by nan-wang** [comment]
recheckcla

**Comment by nan-wang** [comment]
@atibaup Many thanks for your contributions. Would you please sign the CLA above?

**Comment by atibaup** [comment]
> @atibaup Many thanks for your contributions. Would you please sign the CLA above?

Yes @nan-wang : 

**_I have read the CLA Document and I hereby sign the CLA_**


I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
