### PR TITLE
ci: add black

### PR DESCRIPTION
**Pull request by cristianmtr**
- [x] blackify entire code base
- [x] add pre-commit hook for black
- [x] add CI for checking code adheres to black style
- [x] add black badge to our README.md
- [x] guide on restoring git blame

NOTE: Since this PR edits the entire codebase, I had to remove the CI for checking docstrings. I will re-enable this after this PR is merged.

NOTE: This will obfuscate the git blame history. Added note to CONTRIBUTING.md about how to restore it.

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
Let's wait for the CI/CD to be in proper shape

**Comment by hanxiao** [comment]
> NOTE: This will obfuscate the git blame history. This can be fixed using this guide: https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame

⚠️ the blame history needs to be preserved

**Comment by cristianmtr** [comment]
> > NOTE: This will obfuscate the git blame history. This can be fixed using this guide: [psf/black#migrating-your-code-style-without-ruining-git-blame](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame)
> 
>  the blame history needs to be preserved

That can't happen if we do this. 

And as I said, it's trivial to set up git to ignore this specific commit in its blame detection

**Comment by JoanFM** [comment]
> > > NOTE: This will obfuscate the git blame history. This can be fixed using this guide: [psf/black#migrating-your-code-style-without-ruining-git-blame](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame)
> > 
> > 
> > the blame history needs to be preserved
> 
> That can't happen if we do this.
> 
> And as I said, it's trivial to set up git to ignore this specific commit in its blame detection

Can we maybe ensure it works with a change in just one file? As read there, it does not play well with github UI that is what a lot of people use Blame with

**Comment by bwanglzu** [comment]
how about like docstrings, we do incremental update with pre-commit hook?

**Comment by cristianmtr** [comment]
> how about like docstrings, we do incremental update with pre-commit hook?

Could be an option. The problem is that so many PRs will contain a lot of noise.

**Review by hanxiao — APPROVED** [review]

**Pull request merged**
