### PR TITLE
docs(101 ar): added arabic translation to the jina 101 chapter

### PR DESCRIPTION
**Pull request by boussoffara**

### CODE REVIEW

**Comment by hanxiao** [comment]
recheckcla

**Comment by boussoffara** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by boussoffara** [comment]
recheckcla

**Comment by hanxiao** [comment]
hi @boussoffara thanks for your contribution. Unfortunately, as you didn't set up your local `git config` correctly, the author of your commit does not match with your github account. This poses problems:

- Your contribution can not be credited, and will not show up in the list of contributors (as bad `git config` = anonymous)
- We can not accept CLA for anonymous contribution.

**Comment by boussoffara** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by boussoffara** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by boussoffara** [comment]
recheckcla

**Comment by boussoffara** [comment]
@hanxiao Thank you so much for the quick reply, I'm excited about contributing. I apologies  for my multiple attempts but I believe I finally fixed the CLA / author config issue.

**Comment by hanxiao** [comment]
looks good! could you please also add a link from https://github.com/jina-ai/jina#getting-started and point to the arabic version? That will help readers to find this page.

image

**Comment by hanxiao** [comment]
looks good!

**Pull request merged**
