### PR TITLE
docs(readme): fix link

### PR DESCRIPTION
**Pull request by YikSanChan**

### CODE REVIEW

**Comment by hanxiao** [comment]
great, could you please fix it also in other languages? batch replace `README.cn.md` -> `README.zh.md` everywhere

**Comment by YikSanChan** [comment]
@hanxiao done

**Comment by hanxiao** [comment]
recheckcla

**Comment by YikSanChan** [comment]
recheckcla

**Comment by hanxiao** [comment]
❤️ thanks a lot for your contribution!

**Pull request merged**
