### PR TITLE
fix(indexer): format json data before load in get query handler

### PR DESCRIPTION
**Pull request by xubiuit**
`JSONDecodeError:` Expecting value: line 1 column 1 (char 0)`
More details at: https://stackoverflow.com/a/18460958/8339986

### CODE REVIEW

**Comment by hanxiao** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

**Comment by xubiuit** [comment]
Hi @hanxiao, can you please recheck the commit message? Thanks.

**Comment by hanxiao** [comment]
if it passes, you will see a green check here, otherwise please click Details to check why it fails
image

**Comment by xubiuit** [comment]
thank @hanxiao . It has turned green now

**Comment by hanxiao** [comment]
image

**Comment by hanxiao** [comment]
image

**Comment by xubiuit** [comment]
hi @hanxiao, can you take a look?

image

**Comment by xubiuit** [comment]
there is a issue with logic check file existing in test_index

image

**Comment by xubiuit** [comment]
Unit test has failed at `jina.peapods.zmq.Zmqlet`

image

**Comment by JoanFM** [comment]
Hello @xubiuit, there are some conflicts in the PR. Could you please solve them?

**Pull request closed without merging**
