### PR TITLE
docs: add ukrainian translation for readme

### PR DESCRIPTION
**Pull request by Syarol**
For issue #1119

### CODE REVIEW

**Comment by JoanFM** [comment]
recheckcla

**Review by JoanFM — DISMISSED** [review]
need to sign CLA

**Comment by Syarol** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by bhavsarpratik — APPROVED** [review]

**Comment by bhavsarpratik** [comment]
Thanks a lot @Syarol 👍

**Pull request merged**
