### PR TITLE
fix: consistent id of routes

### PR DESCRIPTION
**Pull request by JoanFM**
This is how the `routes` look before the `change` (look of the `pod_id` of the first `route` compared with the rest.

```routes {
  pod: "gateway"
  pod_id: "61eeb411-65ff-40b6-9444-19812524c3f8"
  start_time {
    seconds: 1611735906
    nanos: 103105000
  }
  end_time {
    seconds: 1611735906
    nanos: 120466000
  }
}
routes {
  pod: "indexer/head/ZEDRuntime"
  pod_id: "0x7f7ab9d88990"
  start_time {
    seconds: 1611735906
    nanos: 104699000
  }
  end_time {
    seconds: 1611735906
    nanos: 107112000
  }
}
routes {
  pod: "indexer/2/ZEDRuntime"
  pod_id: "0x7f7ab9daf690"
  start_time {
    seconds: 1611735906
    nanos: 108528000
  }
  end_time {
    seconds: 1611735906
    nanos: 113321000
  }
}
routes {
  pod: "indexer/tail/ZEDRuntime"
  pod_id: "0x7f7ab9de33d0"
  start_time {
    seconds: 1611735906
    nanos: 116263000
  }
  end_time {
    seconds: 1611735906
    nanos: 118584000
  }
}
routes {
  pod: "gateway"
  pod_id: "0x7f7ab9dafd10"
  start_time {
    seconds: 1611735906
    nanos: 120375000
  }
}

```

This is how it looks after this change:

```
routes {
  pod: "gateway"
  pod_id: "8b60c1c5-4493-4e00-ae68-2a1fabe40f27"
  start_time {
    seconds: 1611736251
    nanos: 478771000
  }
  end_time {
    seconds: 1611736251
    nanos: 491130000
  }
}
routes {
  pod: "indexer/head/ZEDRuntime"
  pod_id: "dc9c57cd-93b8-4252-82a3-efb1ef26f2e5"
  start_time {
    seconds: 1611736251
    nanos: 479589000
  }
  end_time {
    seconds: 1611736251
    nanos: 480960000
  }
}
routes {
  pod: "indexer/2/ZEDRuntime"
  pod_id: "dc9c57cd-93b8-4252-82a3-efb1ef26f2e5"
  start_time {
    seconds: 1611736251
    nanos: 481662000
  }
  end_time {
    seconds: 1611736251
    nanos: 487830000
  }
}
routes {
  pod: "indexer/tail/ZEDRuntime"
  pod_id: "dc9c57cd-93b8-4252-82a3-efb1ef26f2e5"
  start_time {
    seconds: 1611736251
    nanos: 489147000
  }
  end_time {
    seconds: 1611736251
    nanos: 490259000
  }
}
routes {
  pod: "gateway"
  pod_id: "8b60c1c5-4493-4e00-ae68-2a1fabe40f27"
  start_time {
    seconds: 1611736251
    nanos: 491094000
  }
}
```

### CODE REVIEW

**Review by hanxiao — CHANGES_REQUESTED** [review]
this change was introduced in https://github.com/jina-ai/jina/pull/1753/files#diff-d9002011181954eeec0b9b94a9d08f7bc8028338275a35bea7823aa07d08041d on purpose to remove the association from zmq to CLI identity.

**Comment by hanxiao** [comment]
https://jinaai.slack.com/archives/C01C04N2UA2/p1611140763065300?thread_ts=1611139604.063900&cid=C01C04N2UA2 discussion thread here.

- I would change the other way, i.e only change `gateway`'s "pod_id"
- don't let the same "pod_id" confuse you, it overexaggerates its purpose, the only usage of it is to sort and unique the `routes` so that it can be prettyprinted. No other single uses.

**Comment by hanxiao** [comment]
im going to make another PR on this one, to change protobuf on `routes.pod_id` to `routes.bultin_id` and comment it as `the address of the object in memory`. 

Right now I'm removing *all* unnecessary "identity" to keep it simple & flexible to extend in the futre.

**Comment by JoanFM** [comment]
> im going to make another PR on this one, to change protobuf on `routes.pod_id` to `routes.bultin_id` and comment it as `the address of the object in memory`.
> 
> Right now I'm removing _all_ unnecessary "identity" to keep it simple & flexible to extend in the futre.

Good for me as long as it is consistent

**Comment by hanxiao** [comment]
this work has been covered in #1865

**Pull request closed without merging**
