### PR TITLE
fix: fix dependency

### PR DESCRIPTION
**Pull request by samsja**
Goals: delete useless dependency from core to keep it as minimal as possible

- [x] remove `prometheus_client` from core dependency
- [x] remove `packaging` from core dependency

### CODE REVIEW

**Review by JoanFM — APPROVED** [review]

**Comment by samsja** [comment]
Please don't merge we still need to take care of the packaging things ( @JohannesMessner )

**Comment by JohannesMessner** [comment]
Like suggested, I changed to using `distutils` for version parsing.
But note that **distutils will be deprecated and removed**: https://peps.python.org/pep-0632/

Also, version checking for plugins seems to not work when using multiprocessing, but this is a different issue.

**Comment by JohannesMessner** [comment]
I will remove distutils and replace it with packaging, instead of the other way around. Low prio for now, will return to this.

**Comment by JohannesMessner** [comment]
Looks like `distutils` is already gone on master. Closing.

**Pull request closed without merging**
