### PR TITLE
docs(readme): improve russian readme

### PR DESCRIPTION
**Pull request by generall**

### CODE REVIEW

**Comment by alexcg1** [comment]
Спасибо for the PR! We may need a bit of time to look it over since I'm not sure many of us speak Russian, but we'll get back to you as soon as we can.

спокойной ночи из Новой Зеландии!

**Comment by nan-wang** [comment]
recheckcla

**Comment by nan-wang** [comment]
@generall hi, would you please sign the CLA above so that we can proceed to merge the PR?

**Comment by generall** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
