### PR TITLE
fix: OpenTelemetry do not force parameter

### LINKED ISSUE #5482: support opentelemetry export more params like headers
**Describe the bug**

jina init param
image

opentelemetry init param
image

**Describe how you solve it**

apm like uptrace https://github.com/uptrace/uptrace will need opentelemetry header to collect information, now jina not support pass header to tracer and meter

---

**Environment**

**Screenshots**

### PR DESCRIPTION
**Pull request by big-thousand**
**Goals:**

fix otel grpc connect default insecure
It should get from env var

- resolves #5482

### CODE REVIEW

**Comment by girishc13** [comment]
@big-thousand Please re-write the commit message as `fix: don't hardcode otel exporter insecure flag`. The important fix is to use the format as `fix: ...`.

Otherwise the PR looks good.

**Comment by girishc13** [comment]
By the way these are the reference code implementations that I looked at:

- https://github.com/open-telemetry/opentelemetry-python/blob/e4a4410dc046f011194eff78e801fb230961eec8/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py#L88-L91
- https://github.com/open-telemetry/opentelemetry-python/blob/e4a4410dc046f011194eff78e801fb230961eec8/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py#L233-L243

**Comment by girishc13** [comment]
@big-thousand I'm working on fixing the test cases after which we can merge this pull request.

**Comment by JoanFM** [comment]
Hey @big-thousand ,  may u rebase your PR with master?

**Comment by JoanFM** [comment]
Thanks a lot for your contribution @big-thousand

**Pull request merged**
