### PR TITLE
docs: add korean translation of readme

### PR DESCRIPTION
**Pull request by NickCwh**

### CODE REVIEW

**Comment by bhavsarpratik** [comment]
recheckcla

**Comment by bwanglzu** [comment]
hi @NickCwh can you check your cla?

**Comment by bhavsarpratik** [comment]
Hey @NickCwh, thanks for contributing. The commit message needs to be overwritten to `docs: add korean translation of readme` by `amending` it.

**Comment by NickCwh** [comment]
I have read the CLA Document and I hereby sign the CLA.
Thanks @bwanglzu for the reminder.

**Review by bhavsarpratik — APPROVED** [review]

**Comment by bhavsarpratik** [comment]
Thanks @NickCwh :)

**Pull request merged**
