### PR TITLE
docs(101): restructure, rewrite

### PR DESCRIPTION
**Pull request by alexcg1**
* New sections to give overview of WHAT Jina is and WHY neural search
* Rewrite of all content - improve English, add analogies
* Move YAML stuff to bottom - YAML only explains how to configure and not an "active agent" the way other things are

NOTE: I've put a few comments in bold: I need feedback on these from @hanxiao @nan-wang 

NEXT: Split into 101 (what, why, how get started) and 102 (how it all actually works)

### CODE REVIEW

**Comment by hanxiao** [comment]
Hi Alex, 

1. check your github notification
image
or go to https://github.com/jina-ai/ and accept the invitation to the our github org.

2. next time you can directly work on **a new branch under** `jina-ai/jina`, instead of your own fork. This enables more comprehensive features in teh CICD pipeline, e.g. PR labeling.

3. btw the your commit message is in bad style, maybe change it to `docs(101): restructure, rewrite`. use `git commit --amend` and `git push --force` to change previous commit message

**Comment by alexcg1** [comment]
Hi Han,

Thanks for the feedback. Accepted invite and fixed the commit.
________________________________

**Comment by alexcg1** [comment]
Hey all, should I just merge this myself now that I'm on the team? Or should one of you check first?

**Comment by hanxiao** [comment]
still need review first. 

btw the commit message are not fixed? Don't forget `git push --force` after `git commit --amend`.

image

**Comment by alexcg1** [comment]
> still need review first.

Sure thing. I put a question in there in bold about some stuff I didn't understand, so that'll need to be answered before it goes live anyway

> 
> btw the commit message are not fixed? Don't forget `git push --force` after `git commit --amend`.

Strange. I did exactly those steps the other day. Seems to have had no result. I just repeated them now, and again, no result

**Correction:** It went through, but didn't change the commit message. 
Screenshot from 2020-06-17 12-15-13

**Comment by alexcg1** [comment]
I'll look into changing **all** the commit messages now

**Comment by alexcg1** [comment]
OK, seems to have worked. I ended up following instructions at https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message

**Pull request merged**
