### PR TITLE
chore(style): update the Dockerfile style

### PR DESCRIPTION
**Pull request by hongchhe**
It's just an suggestion. I think this style is more readable than the old one.

### CODE REVIEW

**Comment by bwanglzu** [comment]
are there any style guide or automatic formatting tools when writing a docker file?

**Comment by bwanglzu** [comment]
I was looking at the docker [official style guide](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), seems they did not use tabs or four spaces?

**Comment by hongchhe** [comment]
> are there any style guide or automatic formatting tools when writing a docker file?

Sorry, there are no style guide. I just find from someone good example and I think it's better. Therefore , it's just a suggestion.

**Comment by hongchhe** [comment]
> I was looking at the docker [official style guide](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), seems they did not use tabs or four spaces.

The whitespace is just used for keeping the contents in line up and down and each command will take one line

**Comment by bwanglzu** [comment]
@hongchhe get it, thanks. I'll let others to decide.

**Comment by JoanFM** [comment]
Hello @hongchhe, Thank you very much for the suggestions, but we prefer to stick with the current version.

**Pull request closed without merging**
