### PR TITLE
JINACORE-119 docs: try to improve documentation on extra dependencies

### PR DESCRIPTION
**Pull request by JoanFM**
**Changes introduced**
Try to improve documentation about extra dependencies used in jina

- Simplify `extra-requirements.txt` @hanxiao @nan-wang do all these `crafter` and `encoder` make sense or is it better to keeep more oriented towards `nlp` , `cv`, `audio`? It feels like we are mixing orthogonal concepts in the kind of tags we are using

@alexcg1 any idea on how to make it look nice?

### CODE REVIEW

**Comment by alexcg1** [comment]
* Under [Extra dependencies explained](https://github.com/jina-ai/jina/blob/c3765f845fa86a0a5852dc95142a105ff1d11728/docs/chapters/install/via-pip.md#extra-dependencies-explained) we could include their logos in a new column on the left, and link the logo to their website. That way we promote our stack and show we're good open-source citizens.
* Description in table is `preformatted text`. Normally I'd only use this for something the user types in, or something the shell prints out, not explanatory text. Maybe that's just me though :wink: 

Other than that, I think it looks nice already - no distractions, clear, easy to read, good layout. I can edit up the English tomorrow.

**Comment by hanxiao** [comment]
> Under Extra dependencies explained we could include their logos in a new column on the left, and link the logo to their website. That way we promote our stack and show we're good open-source citizens.

This can be done in a separate PR by the dev rel team.

**Comment by hanxiao** [comment]
@JoanFM 

Your proposed is not an exhaustive list. You can use the following code to enumerate all of them

```python
import sys

PY37 = 'py37'
PY38 = 'py38'

if sys.version_info >= (3, 8, 0):
    py_tag = PY38
elif sys.version_info >= (3, 7, 0):
    py_tag = PY37
else:
    raise OSError('Jina requires python 3.7 and above, but yours is %s' % sys.version_info)


def get_extra_requires(path, add_all=True):
    import re
    from collections import defaultdict
    try:
        with open(path) as fp:
            extra_deps = defaultdict(set)
            for k in fp:
                if k.strip() and not k.startswith('#'):
                    tags = set()
                    if ':' in k:
                        k, v = k.split(':')
                        tags.update(vv.strip() for vv in v.split(','))
                    tags.add(re.split('[<=>]', k)[0])
                    for t in tags:
                        extra_deps[t].add(k)
                    if PY37 not in tags and PY38 not in tags:
                        # no specific python version required
                        extra_deps[PY37].add(k)
                        extra_deps[PY38].add(k)

            # add tag `all` at the end
            if add_all:
                extra_deps['all'] = set(vv for v in extra_deps.values() for vv in v)
                extra_deps['match-py-ver'] = extra_deps[py_tag]

        return extra_deps
    except FileNotFoundError:
        return {}


print('| extras | will install | description | ')
print('| --- | --- | --- | ')
for k, v in get_extra_requires('extra-requirements.txt').items():
    print(f'| `{k}` | {" ".join(vv for vv in v)} | |')
```

which gives

| extras | will install | description | 
| --- | --- | --- | 
| `numeric` | scipy==1.4.1 | |
| `scipy` | scipy==1.4.1 | |
| `index` | ngt scipy==1.4.1 nmslib plyvel pymilvus annoy | |
| `py37` | sklearn librosa==0.7.2 deepsegment pymilvus ngt numba<=0.48 uvloop flair onnxruntime gevent nmslib flask torch transformers python-magic scipy==1.4.1 onnx torchvision Pillow tensorflow-hub annoy flask_cors librosa docker jieba paddlehub plyvel paddlepaddle tensorflow>=2.0 lz4 | |
| `py38` | sklearn librosa==0.7.2 deepsegment pymilvus numba<=0.48 uvloop flair gevent nmslib flask torch transformers python-magic scipy==1.4.1 torchvision Pillow annoy flask_cors librosa docker jieba plyvel tensorflow>=2.0 lz4 | |
| `sse` | flask_cors flask | |
| `http` | flask_cors gevent flask python-magic | |
| `flask` | flask | |
| `devel` | flask_cors uvloop docker python-magic gevent flask lz4 | |
| `flask_cors` | flask_cors | |
| `nmslib` | nmslib | |
| `flow` | docker | |
| `docker` | docker | |
| `torch` | torch | |
| `framework` | torch sklearn onnx onnxruntime paddlehub torchvision tensorflow-hub paddlepaddle tensorflow>=2.0 | |
| `nlp` | jieba transformers deepsegment flair | |
| `transformers` | transformers | |
| `encode` | transformers flair | |
| `flair` | flair | |
| `paddlepaddle` | paddlepaddle | |
| `paddlehub` | paddlehub | |
| `Pillow` | Pillow | |
| `cv` | Pillow | |
| `tensorflow` | tensorflow>=2.0 | |
| `tensorflow-hub` | tensorflow-hub | |
| `torchvision` | torchvision | |
| `onnx` | onnx | |
| `onnxruntime` | onnxruntime | |
| `annoy` | annoy | |
| `sklearn` | sklearn | |
| `plyvel` | plyvel | |
| `craft` | jieba deepsegment | |
| `jieba` | jieba | |
| `preprocess` | jieba deepsegment | |
| `network` | lz4 | |
| `production` | lz4 | |
| `lz4` | lz4 | |
| `optimization` | lz4 uvloop | |
| `gevent` | gevent | |
| `python-magic` | python-magic | |
| `pymilvus` | pymilvus | |
| `librosa` | librosa==0.7.2 librosa | |
| `audio` | librosa==0.7.2 numba<=0.48 librosa | |
| `deepsegment` | deepsegment | |
| `ngt` | ngt | |
| `numba` | numba<=0.48 | |
| `uvloop` | uvloop | |
| `all` | sklearn librosa==0.7.2 deepsegment pymilvus ngt numba<=0.48 uvloop flair onnxruntime gevent nmslib flask torch transformers python-magic scipy==1.4.1 onnx torchvision Pillow tensorflow-hub annoy flask_cors librosa docker jieba paddlehub plyvel paddlepaddle tensorflow>=2.0 lz4 | |
| `match-py-ver` | sklearn librosa==0.7.2 deepsegment pymilvus ngt numba<=0.48 uvloop flair onnxruntime gevent nmslib flask torch transformers python-magic scipy==1.4.1 onnx torchvision Pillow tensorflow-hub annoy flask_cors librosa docker jieba paddlehub plyvel paddlepaddle tensorflow>=2.0 lz4 | |

**Comment by JoanFM** [comment]
> @JoanFM What you proposed is not an exhaustive list. You can use the following code to enumerate all of them. And for this reason, I would not add logo for each of them for the sake of maintenance.
> 
> ```python
> import sys
> 
> PY37 = 'py37'
> PY38 = 'py38'
> 
> if sys.version_info >= (3, 8, 0):
>     py_tag = PY38
> elif sys.version_info >= (3, 7, 0):
>     py_tag = PY37
> else:
>     raise OSError('Jina requires python 3.7 and above, but yours is %s' % sys.version_info)
> 
> 
> def get_extra_requires(path, add_all=True):
>     import re
>     from collections import defaultdict
>     try:
>         with open(path) as fp:
>             extra_deps = defaultdict(set)
>             for k in fp:
>                 if k.strip() and not k.startswith('#'):
>                     tags = set()
>                     if ':' in k:
>                         k, v = k.split(':')
>                         tags.update(vv.strip() for vv in v.split(','))
>                     tags.add(re.split('[<=>]', k)[0])
>                     for t in tags:
>                         extra_deps[t].add(k)
>                     if PY37 not in tags and PY38 not in tags:
>                         # no specific python version required
>                         extra_deps[PY37].add(k)
>                         extra_deps[PY38].add(k)
> 
>             # add tag `all` at the end
>             if add_all:
>                 extra_deps['all'] = set(vv for v in extra_deps.values() for vv in v)
>                 extra_deps['match-py-ver'] = extra_deps[py_tag]
> 
>         return extra_deps
>     except FileNotFoundError:
>         return {}
> 
> 
> print('| extras | will install | description | ')
> print('| --- | --- | --- | ')
> for k, v in get_extra_requires('extra-requirements.txt').items():
>     print(f'| `{k}` | {" ".join(vv for vv in v)} | |')
> ```
> 
> which gives
> 
> extras	will install	description
> `numeric`	scipy==1.4.1	
> `scipy`	scipy==1.4.1	
> `index`	ngt scipy==1.4.1 nmslib plyvel pymilvus annoy	
> `py37`	sklearn librosa==0.7.2 deepsegment pymilvus ngt numba<=0.48 uvloop flair onnxruntime gevent nmslib flask torch transformers python-magic scipy==1.4.1 onnx torchvision Pillow tensorflow-hub annoy flask_cors librosa docker jieba paddlehub plyvel paddlepaddle tensorflow>=2.0 lz4	
> `py38`	sklearn librosa==0.7.2 deepsegment pymilvus numba<=0.48 uvloop flair gevent nmslib flask torch transformers python-magic scipy==1.4.1 torchvision Pillow annoy flask_cors librosa docker jieba plyvel tensorflow>=2.0 lz4	
> `sse`	flask_cors flask	
> `http`	flask_cors gevent flask python-magic	
> `flask`	flask	
> `devel`	flask_cors uvloop docker python-magic gevent flask lz4	
> `flask_cors`	flask_cors	
> `nmslib`	nmslib	
> `flow`	docker	
> `docker`	docker	
> `torch`	torch	
> `framework`	torch sklearn onnx onnxruntime paddlehub torchvision tensorflow-hub paddlepaddle tensorflow>=2.0	
> `nlp`	jieba transformers deepsegment flair	
> `transformers`	transformers	
> `encode`	transformers flair	
> `flair`	flair	
> `paddlepaddle`	paddlepaddle	
> `paddlehub`	paddlehub	
> `Pillow`	Pillow	
> `cv`	Pillow	
> `tensorflow`	tensorflow>=2.0	
> `tensorflow-hub`	tensorflow-hub	
> `torchvision`	torchvision	
> `onnx`	onnx	
> `onnxruntime`	onnxruntime	
> `annoy`	annoy	
> `sklearn`	sklearn	
> `plyvel`	plyvel	
> `craft`	jieba deepsegment	
> `jieba`	jieba	
> `preprocess`	jieba deepsegment	
> `network`	lz4	
> `production`	lz4	
> `lz4`	lz4	
> `optimization`	lz4 uvloop	
> `gevent`	gevent	
> `python-magic`	python-magic	
> `pymilvus`	pymilvus	
> `librosa`	librosa==0.7.2 librosa	
> `audio`	librosa==0.7.2 numba<=0.48 librosa	
> `deepsegment`	deepsegment	
> `ngt`	ngt	
> `numba`	numba<=0.48	
> `uvloop`	uvloop	
> `all`	sklearn librosa==0.7.2 deepsegment pymilvus ngt numba<=0.48 uvloop flair onnxruntime gevent nmslib flask torch transformers python-magic scipy==1.4.1 onnx torchvision Pillow tensorflow-hub annoy flask_cors librosa docker jieba paddlehub plyvel paddlepaddle tensorflow>=2.0 lz4	
> `match-py-ver`	sklearn librosa==0.7.2 deepsegment pymilvus ngt numba<=0.48 uvloop flair onnxruntime gevent nmslib flask torch transformers python-magic scipy==1.4.1 onnx torchvision Pillow tensorflow-hub annoy flask_cors librosa docker jieba paddlehub plyvel paddlepaddle tensorflow>=2.0 lz4

I was adding everything in the list. It was just a `Draft` to show where it was going

**Comment by JoanFM** [comment]
@hanxiao , would it be easier to present it in reverse? like given a tag, its dependencies? or explain a little bit each dependency saying for what is it needed?

**Pull request merged**
