### PR TITLE
feat: add clear method

### PR DESCRIPTION
**Pull request by AnudeepGunukula**
Hi , i have added a clear method in daemon/clients/base.py which makes a  "delete"
request to api.

This pr might solve the issue #3024 .

### CODE REVIEW

**Comment by nan-wang** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)
#553 :bookmark: Commit Message Guideline for the First Time Contributor

**Comment by deepankarm** [comment]
Hi @AnudeepGunukula, thanks for raising the PR. In addition to fixing the commit message, can you please add a tests for the `clear` method [here](https://github.com/jina-ai/jina/blob/master/tests/distributed/test_workspaces/test_remote_workspaces.py#L134)?

**Comment by AnudeepGunukula** [comment]
Hi, thankyou for your inputs. i will add the tests and also modify the commit message.

**Comment by AnudeepGunukula** [comment]
Hi , i have just tried to rename the last commit, i made using reword
but something happened , please let me know is this fine

**Pull request closed without merging**
