### PR TITLE
feat: pass environment to head and gateway

### PR DESCRIPTION
**Pull request by JoanFM**
# Pull Request Title

## Description

Allow to pass the environments passed to Executors to the Head, and the one from Flow to the Gateway

### CODE REVIEW

**Review by jacobowitz — CHANGES_REQUESTED** [review]
lets add a test for this feature?

**Comment by JoanFM** [comment]
> lets add a test for this feature?

How would u do so?

**Comment by jacobowitz** [comment]
> > lets add a test for this feature?
> 
> How would u do so?

Write a test with a Flow where the envs are set differently for the Gateway and the head and then assert on that?

**Comment by JoanFM** [comment]
> > > lets add a test for this feature?
> > 
> > 
> > How would u do so?
> 
> Write a test with a Flow where the envs are set differently for the Gateway and the head and then assert on that?

but I have no access to the env variables on those Processes right?

**Pull request merged**
