### PR TITLE
docs(readme): fix some typos in zh

### PR DESCRIPTION
**Pull request by ericsyh**
## Background
When checking the ZH ReadMe, i found several typos like needless period, needless space。 

## What did i change
I fixed these typos in this PR. 

Before the change: 
image

After the change:
image

## Test
No code change.

### CODE REVIEW

**Comment by hanxiao** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

**Comment by ericsyh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ericsyh** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by ericsyh** [comment]
recheckcla

**Comment by JoanFM** [comment]
recheckcla

**Comment by ericsyh** [comment]
@JoanFM Hi Joan, i saw the failure of label-pr CI check. Does this CI aims to check whether the PR labeled or not? Seems no permission for me to add the label.

**Comment by JoanFM** [comment]
@ericsyh do not worry, it is not a required step. It tries to label automatically depending on the areas of code but fails for some Readme. But it does not block the merging. So thank you very much for the contribution!

**Comment by alexcg1** [comment]
@all-contributors please add @ericsyh   for doc

**Pull request merged**
