### PR TITLE
docs(other-distros): initial commit

### LINKED ISSUE #869: Docs: Using Docker images on Fedora
**Describe the feature**
I've recently started using Fedora 32 and hit some issues running the Jina Docker images. These are issues from Docker itself, but I still think we should mention them in the docs. Perhaps a new page - "Using anything **other** than Mac/Ubuntu? Check here!"

These aren't Jina's issues, but they will screw up using Jina on a new machine, so I think users should at least be aware

**Your proposal**

* [Inform users they need to add an extra kernel line](https://github.com/jitsi/docker-jitsi-meet/issues/618#issuecomment-636327655)
* [Inform them to disable SELinux](https://stackoverflow.com/questions/61527193/docker-and-permissionerror-errno-13-permission-denied-output-svg)

After fixing those, Jina's Hello World worked perfectly!

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-193) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by alexcg1**
Fixes #869 - explains common errors on Fedora. Over time we can expand this page to take into account other distros that don't work as perfectly as Ubuntu

### CODE REVIEW

**Review by hanxiao — CHANGES_REQUESTED** [review]
Hi Alex, I think you need this filename (without extension) to `docs/index.rst` otherwise it wont index

**Comment by alexcg1** [comment]
Done!

**Comment by hanxiao** [comment]
duplicate files?

**Review by hanxiao — CHANGES_REQUESTED** [review]
duplicate files?

**Comment by alexcg1** [comment]
Whoops. Fixed

**Review by hanxiao — APPROVED** [review]

**Pull request merged**
