### PR TITLE
docs: fix the type error

### PR DESCRIPTION
**Pull request by hongchhe**
1. import the numpy
2. fix the "TypeError: 'builtin_function_or_method' object is not subscriptable"

### CODE REVIEW

**Comment by JoanFM** [comment]
Hello @hongchhe , please change the commit message. Our lint complains about the full-stop at the end.

You can ammend ur commit and change it!

**Comment by hongchhe** [comment]
> Hello @hongchhe , please change the commit message. Our lint complains about the full-stop at the end.
> 
> You can ammend ur commit and change it!

Thanks, I have updated it.

**Comment by hongchhe** [comment]
Hi Joan, the jinad-test cannot be passed. It seems that the problem don't related with this PR.

**Comment by JoanFM** [comment]
> Hi Joan, the jinad-test cannot be passed. It seems that the problem don't related with this PR.

Sure, not ur fault, is a known issue

**Comment by JoanFM** [comment]
recheckcla

**Comment by JoanFM** [comment]
Thanks for your contribution. Unfortunately, as you didn't set up your local git config correctly, the author of your commit does not match with your Github account. This poses problems:
Your contribution can not be credited, and will not show up in the list of contributors (as bad git config = anonymous)
We can not accept CLA for anonymous contribution.
Please note that this does not only affect your contribution to Jina, but also affects all your contribution to anything on Github. So better fix it, once for all.
Here is what you can do:
```
git config user.name "Correct new name"
git config user.email "correct@new.email" -> match with your Github registered email address
```
Then fix the commit message by
```
git commit --amend --author="Author Name <email@address.com>" --no-edit
git push --force
```

**Comment by hongchhe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by JoanFM — APPROVED** [review]

**Comment by JoanFM** [comment]
Thank you very much for your contribution @hongchhe !!!

**Pull request merged**
