### PR TITLE
corrected minor typo in german 101

### PR DESCRIPTION
**Pull request by Zenahr**

### CODE REVIEW

**Comment by JoanFM** [comment]
Hey @Zenahr,

Thank you very much for contributing,

Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)
#553 :bookmark: Commit Message Guideline for the First Time Contributor
jina-ai/jina | Jun 21st | Added by GitHub
CONTRIBUTING.md
jina-ai/jina | Added by GitHub

**Comment by JoanFM** [comment]
recheckcla

**Comment by Zenahr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JoanFM** [comment]
recheckcla

**Comment by JoanFM** [comment]
Hey @Zenahr, can you please follow the indications I stated in a previous message trying to fix the commit mesage?

**Comment by Zenahr** [comment]
> Hey @Zenahr, can you please follow the indications I stated in a previous message trying to fix the commit mesage? 

Sure, just wanted to get licensing out of the way first.

**Comment by Zenahr** [comment]
I'll make a new PR since I'm running into problems amending the commit message.

**Pull request closed without merging**
