### PR TITLE
fix(consensus): free allocated CStrings

### PR DESCRIPTION
**Pull request by thechampagne**
**Goals:**

- resolves #ISSUE-NUMBER
- ...
- ...

- ...
- ...
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

### CODE REVIEW

**Comment by JoanFM** [comment]
Thank you for the contribution, may I ask how did you spot this error? there may be others in the code.

Thanks

**Comment by JoanFM** [comment]
Would this also require change?

```
LogLevel                 = C.CString(raftDefaultConfig.LogLevel)
```

**Comment by thechampagne** [comment]
> Would this also require change?

Yes it should be freed, totally forgot it.

**Comment by thechampagne** [comment]
> Thank you for the contribution, may I ask how did you spot this error? there may be others in the code.
> 
> Thanks

Reading the code :skull:  not all of it for sure.

**Pull request merged**
