### PR TITLE
feat(encoder): add fastica to numeric encoders

### PR DESCRIPTION
**Pull request by JamesTang616**
Added FastICA to numeric encoders
[https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FastICA.html](url)

### CODE REVIEW

**Comment by hanxiao** [comment]
recheckcla

**Comment by hanxiao** [comment]
recheckcla

**Comment by JamesTang616** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by JamesTang616** [comment]
recheckcla

**Pull request merged**
