### PR TITLE
docs(101): add support to the Spanish language for 101

### PR DESCRIPTION
**Pull request by Immich**

### CODE REVIEW

**Comment by nan-wang** [comment]
@Immich hi, there. Many thanks for your contribution. Would you please take a look into the conflicts?

**Review by theUnkownName — COMMENTED** [review]
The translation looks good 👍  just could you check the conflicts? @Immich

**Comment by Immich** [comment]
Done 🙌

**Review by theUnkownName — APPROVED** [review]
Looks good to me

**Comment by nan-wang** [comment]
recheckcla

**Comment by nan-wang** [comment]
**Jina CLA check**<br/>
  ❤️ Thank you for your pull request. It looks like this is your first contribution to an open source project maintained by Jina AI Limited. Before we can look at your pull request, we kindly ask that you sign our [Contributor License Agreement](https://github.com/jina-ai/jina/blob/master/.github/CLA.md). You can sign it by commenting in format below.
  - - -
  ***I have read the CLA Document and I hereby sign the CLA***
  - - -

**Comment by nan-wang** [comment]
@Immich Would you please sign the CLA above so that we can merge the PR?

**Comment by Immich** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Pull request merged**
