### PR TITLE
ci(unittest): allow test discovery from unittest

### PR DESCRIPTION
**Pull request by JoanFM**
PR linked to #612 

**Changes introduced**

Changing the CI command to execute unittests. This change make several changes necessary in order to pass all the unittests that were not previously being checked.

> Tests under executors.crafters.audio are failing due to the numba version in the system. librosa requires numba version==0.48 because from 0.50 and up it removes decorators which are needed. audio also requires libsndfile1 dependency.

> Tests under indexer keyvalue failing due to missing arguments.

> Adapt extra requirements to successfully run all tests.

> Change relative paths that are broken when run from jina home dir.

> Correct some failing unittests.

### CODE REVIEW

**Comment by JoanFM** [comment]
@nan-wang moving conversation to this PR.

I am aware that librosa is only required for audio module, but if the numba dependency does not brake anything it is better to be able to pass the tests globally.

**Comment by JoanFM** [comment]
Current errors on unittests are:

- Any test related to **audio**: **Missing sndfile library not found**:

> Potential solution: Add to .ci.yml: sudo apt-get install **libsndfile1** at **Install dependencies** step

- Test on **tests/executors/crafterstest_segmenter.py**. It seems that chunks do not get the id expected (incremental id). Is it that expected? Is the test assuming a wrong behavior or does it need a fix?

- Test on **tests/executors/crafters/nlp/test_split.py**. Failing to chunk chinese sentence.

**Comment by hanxiao** [comment]
Man! you did it! Great effort!

I haven't read details yet. @nan-wang please check on this.

One housekeeping remark, as you already a member of our Github org. In the future, you can create a branch directly under `jina-ai/jina` and make a PR from that. You don't need to work on your own fork. In this way, your PR makes `cla-check` and `label-pr` tasks running without permission problem. You will see auto labeling as follows

image

**Comment by hanxiao** [comment]
I had a brief overview of this PR. looks good. I intend to merge it now, as the other PR heavily rely on this. @nan-wang please give it a look when you have time.

**Pull request merged**
