### PR TITLE
ci: classify flow unit test

### PR DESCRIPTION
**Pull request by niuzs-alan**
> [Unit tests parallelism of Jina](https://github.com/jina-ai/jina/blob/master/.github/workflows/ci.yml#L269)

Classify flow unit test and break down the unit test folder, to leverage parallel CI implementation.
- Previous folder: `tests/unit/flow`  
- New folders: 
   - `tests/unit/flow-construct`
   - `tests/unit/flow-orchestrate`
   - `tests/unit/flow-example`

### CODE REVIEW

**Comment by bwanglzu** [comment]
can you elaborate a bit in the thread on how we classify and  how could we put future flow test into different folders?

**Comment by niuzs-alan** [comment]
> can you elaborate a bit in the thread on how we classify and how could we put future flow test into different folders?



> can you elaborate a bit in the thread on how we classify and how could we put future flow test into different folders?

Done.

**Comment by niuzs-alan** [comment]
> can you elaborate a bit in the thread on how we classify and how could we put future flow test into different folders?

Sure!
Here is it:
```
:~/code/jina-ai/jina/tests/unit$ tree flow-* -L 1
flow-construct
├── __init__.py
├── mwu-encoder
├── __pycache__
├── test_flow_enter_error.py
├── test_flow_except.py
├── test_flow.py
├── test_flow_skip.py
├── test_flow_start_noblock.py
├── test_flow_visualization.py
├── test_flow_yaml_parser.py
├── test_slow_executor_shutdown.py
└── yaml
flow-example
├── __init__.py
├── __pycache__
├── test_flow_example_face.py
├── test_flow_example_faiss.py
├── test_flow_segmenter.py
└── yaml
flow-orchestrate
├── __init__.py
├── __pycache__
├── test_asyncflow.py
├── test_flow_before_after.py
├── test_flow_change_gateway.py
├── test_flow_dynamic_routing.py
├── test_flow_http_extend.py
├── test_flow_merge.py
├── test_remote_orchestrate.py
└── yaml
```

**Comment by hanxiao** [comment]
lgtm, just fyi on the timing 
image

**Review by hanxiao — APPROVED** [review]

**Pull request merged**
