### PR TITLE
docs(contributing): instructions for github association

### PR DESCRIPTION
**Pull request by Morriaty-The-Murderer**

### CODE REVIEW

**Comment by Morriaty-The-Murderer** [comment]
BTW, I am not sure the files in `docs` directory is auto-generated or mannully-edited. So I haven't modified the `docs/chapters/CONTRIBUTING.md`.

**Comment by alexcg1** [comment]
Thanks for the PR Morriaty! One thing to add: On point one, I would add "If this is your first time using git" - some users may be experienced git users but first-time Jina contributors.

Cheers :)

**Comment by Morriaty-The-Murderer** [comment]
> Thanks for the PR Morriaty! One thing to add: On point one, I would add "If this is your first time using git" - some users may be experienced git users but first-time Jina contributors.
> 
> Cheers :)

Added~

**Comment by alexcg1** [comment]
Nice :+1: . Let's wait for one of the team to give a LGTM and we're good as gold

**Comment by hanxiao** [comment]
recheckcla

**Pull request merged**
