### PR TITLE
docs(101): minor typo in german version

### PR DESCRIPTION
**Pull request by Zenahr**
- fixed minor typo.

### CODE REVIEW

**Comment by Zenahr** [comment]
recheckcla

**Comment by Zenahr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hanxiao** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

**Comment by Zenahr** [comment]
> 
> 
> Bad commit message, please refer to:
> 
>     * [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
> 
>     * [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

The commit message is exactly as it should be, no?

>Common mistakes

>  - doc(101): improved 101 document - should be docs(101)

My commit message reads exactly `docs(101)`

**Comment by JoanFM** [comment]
Hey @Zenhar, I think the issue is that your commit message is not a one-liner.

**Comment by Zenahr** [comment]
> Hey @Zenahr, I think the issue is that your commit message is not a one-liner.

Thanks for your reply @JoanFM 
I don't see how the commit message "docs(101)" is not a one-liner. Sorry for the inconvenience but I believe to have followed the guidelines laid out by your contribution guide as cited above. Am I missing something?

**Comment by JoanFM** [comment]
Hey @Zenahr; then you are missing some description of the changes introduced in the commit.

**Comment by Zenahr** [comment]
This is the trace from the commit-lint:

⧗   input: docs(101)

- fixed minor typo.
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

I guess the description can't contain markdown syntax then.

**Pull request closed without merging**
