### PR TITLE
docs: fix typos markdowns

### PR DESCRIPTION
**Pull request by slettner**

### CODE REVIEW

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by nan-wang** [comment]
recheckcla

**Comment by nan-wang** [comment]
hi, @slettner Thanks for the PR. Your contribution is greatly appreciated. Would you please sign the CLA above so that we can proceed to merge this PR?

**Comment by slettner** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
