### PR TITLE
refactor(optimizer): optimizer parameters

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
move params from optimize_flow to OptunaOptimizer __init__

### CODE REVIEW

**Comment by JoanFM** [comment]
maybe we should have this PR agains the other Optimizer branch to better see the changes? or is it intended to substitute it?

**Comment by Yongxuanzhang** [comment]
> maybe we should have this PR agains the other Optimizer branch to better see the changes? or is it intended to substitute it?

This is based on https://github.com/jina-ai/jina/pull/1726 but focuses on a different part.

**Comment by JoanFM** [comment]
> > maybe we should have this PR agains the other Optimizer branch to better see the changes? or is it intended to substitute it?
> 
> This is based on #1726 but focuses on a different part.

that is why if u do the PR onto the branch of #1726 it will be easier to understand the changes of this PR. Right now here everything is mixed up

**Comment by Yongxuanzhang** [comment]
> > > maybe we should have this PR agains the other Optimizer branch to better see the changes? or is it intended to substitute it?
> > 
> > 
> > This is based on #1726 but focuses on a different part.
> 
> that is why if u do the PR onto the branch of #1726 it will be easier to understand the changes of this PR. Right now here everything is mixed up

Did you mean that we should merge this https://github.com/jina-ai/jina/pull/1751 into https://github.com/jina-ai/jina/pull/1726? After pairing with @maximilianwerk and @florian-hoenicke, we think these two could be merged to master independently. Or shall we discuss it?

**Comment by JoanFM** [comment]
> > > > maybe we should have this PR agains the other Optimizer branch to better see the changes? or is it intended to substitute it?
> > > 
> > > 
> > > This is based on #1726 but focuses on a different part.
> > 
> > 
> > that is why if u do the PR onto the branch of #1726 it will be easier to understand the changes of this PR. Right now here everything is mixed up
> 
> Did you mean that we should merge this #1751 into #1726? After pairing with @maximilianwerk and @florian-hoenicke, we think these two could be merged to master independently. Or shall we discuss it?

No, no problem go for it. My point is that rhis branch contains also all the changes of the other PR

**Comment by maximilianwerk** [comment]
> No, no problem go for it. My point is that rhis branch contains also all the changes of the other PR

Exactly. Since you chose my branch as a base branch, I'd like you to merge it back to my branch. Especially, since the tests on my branch are currently not running through and I have to fix them.

**Review by maximilianwerk — APPROVED** [review]
LGTM, well done.

**Pull request merged**
