### PR TITLE
refactor: change cancel runtime logic

### PR DESCRIPTION
**Pull request by JoanFM**
**Changes introduced**
Removes the extra `zmq` context used to communicate from `JinadRuntime` from `Pea` to "cheat" and look like a `ZEDRuntime` is cancelled. Use an event instead

@deepankarm  we can wait for ur big JinaD PR to pass before merging if u want

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200507875159774) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by deepankarm** [comment]
@JoanFM Let's wait for #2473 to merge, please

**Review by hanxiao — CHANGES_REQUESTED** [review]
we used to have event-based communication, however it doesn't work for AsyncRuntime. Deepankar should remember this.

**Comment by JoanFM** [comment]
> @JoanFM Let's wait for #2473 to merge, please

Sure @deepankarm . But lets see if later we can find why this should not work. It passes all tests

**Comment by JoanFM** [comment]
> we used to have event-based communication, however it doesn't work for AsyncRuntime. Deepankar should remember this. 

It seems to work here.
 Anyway I wait for JinaD big refactoring

**Comment by JoanFM** [comment]
> we used to have event-based communication, however it doesn't work for AsyncRuntime. Deepankar should remember this.

Does not seem to have any problem

**Review by hanxiao — APPROVED** [review]

**Pull request merged**
