### PR TITLE
fix: naming of peas/pods/replicas in logs

### LINKED ISSUE #2363: fix naming of pods and replicas in logs
See tests.unit.peapods.pods.test_compound_pods.test_pod_naming_with_parallel

Pod should be `replica`

### PR DESCRIPTION
**Pull request by properGrammar**
Intended to fix #2363 

This is a 2nd, cleaner try at #2382 

cc: @cristianmtr @maximilianwerk @JoanFM

### CODE REVIEW

**Comment by JoanFM** [comment]
recheckcla

**Comment by properGrammar** [comment]
Hey @JoanFM , I just wanna make sure you're not waiting on me to do anything here... I don't think so, but I'm not familiar with y'all's process, so I'm verifying. Thanks!

**Review by cristianmtr — APPROVED** [review]

**Comment by cristianmtr** [comment]
Thanks for carrying this through!

Needs a rebase/merge.

**Comment by properGrammar** [comment]
You're welcome, @cristianmtr ! Glad I could help. 😊

Forgive my ignorance, but is the rebase/merge something that you need me to do, or is that note meant for a different person/process? I'm happy to rebase/merge and push another commit, just let me know, thx.

**Comment by cristianmtr** [comment]
> You're welcome, @cristianmtr ! Glad I could help. 
> 
> Forgive my ignorance, but is the rebase/merge something that you need me to do, or is that note meant for a different person/process? I'm happy to rebase/merge and push another commit, just let me know, thx.

Yeah, the GH PR says there are conflicting files that need to be merged manually.

**Comment by properGrammar** [comment]
@cristianmtr Ok, I spent way too long today trying to rebase/merge to master, but every time I did it Git told me everything was "Already up to date." No matter how many SO posts I looked at, I wasn't able to determine why I was unable to pull the new changes to my local copy of the repo in order to make the rebase/merge meaningful. 

Ultimately, I realized the conflict was that the name of one of the files in this PR had changed since I submitted it, so I just changed it locally, pushed the new commit, and resolved a couple small conflicts on here. Hopefully that does it! and this PR can be approved before this codebase shifts any further, lol...

**Comment by properGrammar** [comment]
I'm seeing the check-black failed, and I'm not sure why. All commit hooks passed locally before the most recent push... 🤷🏻‍♂️

**Comment by cristianmtr** [comment]
> I'm seeing the check-black failed, and I'm not sure why. All commit hooks passed locally before the most recent push... 🤷🏻‍♂️

Not sure how it happened, but a test is failing the black test. It should have been handled by the pre-commit hook.

Can you do `black -S tests/` and commit those changes?

**Comment by properGrammar** [comment]
@JoanFM @cristianmtr  Is there more that needs doing by me on this at the moment? Should I try once more with a new branch/PR; third time's the charm? 😂

**Comment by cristianmtr** [comment]
Looks good for me. Let's see what the CI says

**Comment by cristianmtr** [comment]
Uff seems like GH changes something and now you need to add

```
permissions:
  pull-requests: write
```

to the commit-lint action

**Comment by cristianmtr** [comment]
I cannot reproduce the error from my fork. But I do see your commit messages don't comply with our standards. Can you modify them? Or just squash them into one? https://github.com/jina-ai/jina/blob/84ae65f21f4131e2ba06de1d1bcc6556678f56df/CONTRIBUTING.md#L133

**Comment by properGrammar** [comment]
@cristianmtr 

The offending commit is `resolved some merge conflicts 99d1b19`. It did not occur to me (although it probably should have) that manual merge conflict commits made on GH would need to follow your commit message expectations.

I spent some time looking into how to reword such messages, but am unfortunately not getting results I'm super confident in locally.

Considering that I'm already dissatisfied with the extra unnecessary file changes this PR has picked up, I'm gonna start over one more time in the hopes that I can cleanly submit just the changes you're looking for. Thanks for your patience.

**Comment by properGrammar** [comment]
#2508 resolves this

**Pull request closed without merging**
