### PR TITLE
feat(helloworld): random available port is used instead of 8080

### PR DESCRIPTION
**Pull request by dinis-rodrigues**
Instead of using the default 8080 port, a random available port is used instead for the hello world demo examples.

### CODE REVIEW

**Review by hanxiao — CHANGES_REQUESTED** [review]
i think the frontend part needs to be changed accordingly otherwise it wont know the random port.

**Comment by JoanFM** [comment]
Hello @dinis-rodrigues ,

Did you experience any problem given by the fact that 8080 is given as default port number?

**Comment by JoanFM** [comment]
Closing due to inactivity

**Comment by JoanFM** [comment]
Hello @dinis-rodrigues ,

I am closing this PR due to inactivity, feel free to reopen it whenever you are free to review the suggested changes.

Thank you for your contribution!

**Pull request closed without merging**
