### PR TITLE
test: delete empty space in a filename

### PR DESCRIPTION
**Pull request by YueLiu-jina**
There's an empty space at the end of the filename 'tests/yaml/test-multifield-encoder.yml'. This will cause an 'invalid path error' using git clone in Win10.

### CODE REVIEW

**Comment by hanxiao** [comment]
bad commit message, this is not about doc, rename it to `tests: ...`

**Comment by YueLiu-jina** [comment]
renamed

**Comment by hanxiao** [comment]
this looks very weird. how come remove a space fix `'invalid path error'` on Win10? How are they related and how do you even find it out?

**Comment by YueLiu-jina** [comment]
QQ截图20200621221208

**Comment by YueLiu-jina** [comment]
QQ截图20200621221208

**Comment by YueLiu-jina** [comment]
This was the screenshot of that error. This problem also seems weird to me. I met it when I used git clone last Friday. I tried a lot of ways to solve it, but nothing worked other than renaming it.

**Comment by hanxiao** [comment]
weird but fair enough.

**Pull request merged**
