### PR TITLE
fix(docs): correct the mismatched parameter value

### PR DESCRIPTION
**Pull request by coolmian**
#588

### CODE REVIEW

**Comment by hanxiao** [comment]
Thanks for your contribution. Unfortunately, as you didn't set up your local git config correctly, the author of your commit does not match with your Github account. This poses problems:

- Your contribution can not be credited, and will not show up in the list of contributors (as bad git config = anonymous)
- We can not accept CLA for anonymous contribution.

Please note that this does not only affect your contribution to Jina, but also affects *all your contribution* to anything on Github. So better fix it, once for all.

Here is what you can do:
```bash
git config user.name "Correct new name"
git config user.email "correct@new.email" -> match with your Github registered email address
```

Then fix the commit message by
```bash
git commit --amend --author="Author Name <email@address.com>" --no-edit
git push --force
```

**Comment by coolmian** [comment]
> Thanks for your contribution. Unfortunately, as you didn't set up your local git config correctly, the author of your commit does not match with your Github account. This poses problems:
> 
> * Your contribution can not be credited, and will not show up in the list of contributors (as bad git config = anonymous)
> * We can not accept CLA for anonymous contribution.
> 
> image
> 
> Please note that this does not only affect your contribution to Jina, but also affects _all your contribution_ to anything on Github. So better fix it, once for all.
> 
> Here is what you can do:
> 
> ```shell
> git config user.name "Correct new name"
> git config user.email "correct@new.email" -> match with your Github registered email address
> ```
> 
> Then fix the commit message by
> 
> ```shell
> git commit --amend --author="Author Name <email@address.com>" --no-edit
> git push --force
> ```

Thank you very much for pointing out the problem. I have revised it according to your instructions. Does it meet the requirements now?

**Comment by hanxiao** [comment]
recheckcla

**Comment by hanxiao** [comment]
now you only have to follow what bot said and we are ready to merge

**Comment by coolmian** [comment]
> recheckcla


I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
