### PR TITLE
fix: fix plot, naming and kubernetes

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Comment by hanxiao** [comment]
better to have two screenshots, the native flow, and k8s flow

**Comment by JoanFM** [comment]
> better to have two screenshots, the native flow, and k8s flow

The K8s flow is not solved here. I just found a bug. If u plot a Flow with 2 pods with same executor class, the plot looks a mess because there is no way to tell between the 2 nodes

**Comment by JoanFM** [comment]
Old:
image

New:
image

With Flow description:

```yaml
!Flow
version: '1'
with:
  name: my-flow
  protocol: http
  port_expose: 8080
  infrastructure: JINA
pods:
  - name: encode1
    shards: 2
    replicas: 3
  - name: encode2
    shards: 2
    replicas: 3
```

**Comment by hanxiao** [comment]
please refer to this https://mermaid-js.github.io/mermaid/#/flowchart?id=beta-flowcharts

**Comment by JoanFM** [comment]
New plots:

- Consider everything, Inspection Pods, external, etc ...

image

- With Kubernetes and no inspection Pods.

image

**Comment by hanxiao** [comment]
can i have the `mermaid_str` of these two graphs before ploting? i want to hack the color palette a bit

**Comment by hanxiao** [comment]
image
image

**Comment by hanxiao** [comment]
changed to gray 
image
image

**Pull request merged**
