### PR TITLE
feat(flow): inspect pods are collected before gateway

### PR DESCRIPTION
**Pull request by hanxiao**
## New Feature
- `.gather_inspect()` can be used to manually collect inspect pods
- `--inspect` is added to Flow CLI/API, allowing `HANG`, `REMOVE`, `COLLECT` three modes, 
   - `HANG`: keep those pods where they are
   - `REMOVE`: remove all pods before `.build()`
   - `COLLECT`: all inspect pods are auto-collected via `.gather_inspect()` before `.build()`

```python
f = Flow(no_inspect=True).add(name='p1').add(name='p2', needs='gateway').inspect().needs(['p1', 'p2']).plot()

f = Flow().add(name='p1').add(name='p2', needs='gateway').inspect().needs(['p1', 'p2']).plot()

```

```python
f = Flow().add(name='p1').add(name='p2', needs='gateway').needs(['p1', 'p2']).inspect().plot()
```

```python
f = Flow().add(name='p1', parallel=3).inspect().add(name='p2', needs='gateway').needs(['p1', 'p2']).inspect().plot()
```

<img src="https://mermaid.ink/svg/JSV7aW5pdDogeyd0aGVtZSc6ICdiYXNlJywgJ3RoZW1lVmFyaWFibGVzJzogeyAncHJpbWFyeUNvbG9yJzogJyMzMkM4Q0QnLCAnZWRnZUxhYmVsQmFja2dyb3VuZCc6JyNmZmYnLCAnY2x1c3RlckJrZyc6ICcjRkZDQzY2J319fSUlCmdyYXBoIExSCnN1YmdyYXBoIHAxIFsicDEgKDMpIl0KCXAxX0hFQUQoKGhlYWQpKTo6OnBlYS0tPnAxXzBbW3AxXzBdXTo6OnBlYQoJcDFfMFtbcDFfMF1dOjo6cGVhLS0+cDFfVEFJTCgodGFpbCkpOjo6cGVhCglwMV9IRUFEKChoZWFkKSk6OjpwZWEtLT5wMV8xW1twMV8xXV06OjpwZWEKCXAxXzFbW3AxXzFdXTo6OnBlYS0tPnAxX1RBSUwoKHRhaWwpKTo6OnBlYQoJcDFfSEVBRCgoaGVhZCkpOjo6cGVhLS0+cDFfMltbcDFfMl1dOjo6cGVhCglwMV8yW1twMV8yXV06OjpwZWEtLT5wMV9UQUlMKCh0YWlsKSk6OjpwZWEKZW5kCmdhdGV3YXkoZ2F0ZXdheSk6OjpHQVRFV0FZIC0tPiB8UFVCLVNVQnxwMV9IRUFEKChmYTpmYS1yYW5kb20pKTo6OlBPRApwMV9UQUlMKChmYTpmYS1yYW5kb20pKTo6OlBPRCAtLi0+IHxQVUItU1VCfGluc3BlY3R7e2luc3BlY3R9fTo6OklOU1BFQ1QKcDFfVEFJTCgoZmE6ZmEtcmFuZG9tKSk6OjpQT0QgLS0+IHxQVUItU1VCfF9hdXhfaW5zcGVjdChfYXV4X2luc3BlY3QpOjo6SU5TUEVDVF9BVVhfUEFTUwpnYXRld2F5KGdhdGV3YXkpOjo6R0FURVdBWSAtLT4gfFBVQi1TVUJ8cDIocDIpOjo6UE9ECl9hdXhfaW5zcGVjdChfYXV4X2luc3BlY3QpOjo6SU5TUEVDVF9BVVhfUEFTUyAtLT4gfFBVU0gtUFVMTHxqb2luZXIoam9pbmVyKTo6OkpPSU4KcDIocDIpOjo6UE9EIC0tPiB8UFVTSC1QVUxMfGpvaW5lcihqb2luZXIpOjo6Sk9JTgpqb2luZXIoam9pbmVyKTo6OkpPSU4gLS4tPiB8UFVCLVNVQnxpbnNwZWN0NXt7aW5zcGVjdDV9fTo6OklOU1BFQ1QKam9pbmVyKGpvaW5lcik6OjpKT0lOIC0tPiB8UFVCLVNVQnxfYXV4X2luc3BlY3Q2KF9hdXhfaW5zcGVjdDYpOjo6SU5TUEVDVF9BVVhfUEFTUwpfYXV4X2luc3BlY3Q2KF9hdXhfaW5zcGVjdDYpOjo6SU5TUEVDVF9BVVhfUEFTUyAtLT4gfFBVU0gtUFVMTHxnYXRoZXJfaW5zcGVjdHt7Z2F0aGVyX2luc3BlY3R9fTo6OkpPSU5fSU5TUEVDVAppbnNwZWN0e3tpbnNwZWN0fX06OjpJTlNQRUNUIC0uLT4gfFBVU0gtUFVMTHxnYXRoZXJfaW5zcGVjdHt7Z2F0aGVyX2luc3BlY3R9fTo6OkpPSU5fSU5TUEVDVAppbnNwZWN0NXt7aW5zcGVjdDV9fTo6OklOU1BFQ1QgLS4tPiB8UFVTSC1QVUxMfGdhdGhlcl9pbnNwZWN0e3tnYXRoZXJfaW5zcGVjdH19Ojo6Sk9JTl9JTlNQRUNUCmdhdGhlcl9pbnNwZWN0e3tnYXRoZXJfaW5zcGVjdH19Ojo6Sk9JTl9JTlNQRUNUIC0tPiB8UFVTSC1QVUxMfGdhdGV3YXlfRU5EKGdhdGV3YXkpOjo6R0FURVdBWQpjbGFzc0RlZiBQT0QgZmlsbDojMzJDOENELHN0cm9rZTojMDA5OTk5CmNsYXNzRGVmIElOU1BFQ1QgZmlsbDojZmY2NjY2LGNvbG9yOiNmZmYKY2xhc3NEZWYgSk9JTl9JTlNQRUNUIGZpbGw6I2ZmNjY2Nixjb2xvcjojZmZmCmNsYXNzRGVmIEdBVEVXQVkgZmlsbDojNkU3Mjc4LGNvbG9yOiNmZmYKY2xhc3NEZWYgSU5TUEVDVF9BVVhfUEFTUyBmaWxsOiNmZmYsY29sb3I6IzAwMCxzdHJva2UtZGFzaGFycmF5OiA1IDUKY2xhc3NEZWYgcGVhIGZpbGw6IzAwOTk5OSxzdHJva2U6IzFFNkU3Mw=="/>

```python
f = Flow().add().inspect().add().inspect().add().inspect().plot()

f = Flow(no_inspect=True).add().inspect().add().inspect().add().inspect().plot()
```

<img src="https://mermaid.ink/svg/JSV7aW5pdDogeyd0aGVtZSc6ICdiYXNlJywgJ3RoZW1lVmFyaWFibGVzJzogeyAncHJpbWFyeUNvbG9yJzogJyMzMkM4Q0QnLCAnZWRnZUxhYmVsQmFja2dyb3VuZCc6JyNmZmYnLCAnY2x1c3RlckJrZyc6ICcjRkZDQzY2J319fSUlCmdyYXBoIExSCmdhdGV3YXkoZ2F0ZXdheSk6OjpHQVRFV0FZIC0tPiB8UFVTSC1QVUxMfHBvZDAocG9kMCk6OjpQT0QKcG9kMChwb2QwKTo6OlBPRCAtLi0+IHxQVUItU1VCfGluc3BlY3R7e2luc3BlY3R9fTo6OklOU1BFQ1QKcG9kMChwb2QwKTo6OlBPRCAtLT4gfFBVQi1TVUJ8X2F1eF9pbnNwZWN0KF9hdXhfaW5zcGVjdCk6OjpJTlNQRUNUX0FVWF9QQVNTCl9hdXhfaW5zcGVjdChfYXV4X2luc3BlY3QpOjo6SU5TUEVDVF9BVVhfUEFTUyAtLT4gfFBVU0gtUFVMTHxwb2QzKHBvZDMpOjo6UE9ECnBvZDMocG9kMyk6OjpQT0QgLS4tPiB8UFVCLVNVQnxpbnNwZWN0NHt7aW5zcGVjdDR9fTo6OklOU1BFQ1QKcG9kMyhwb2QzKTo6OlBPRCAtLT4gfFBVQi1TVUJ8X2F1eF9pbnNwZWN0NShfYXV4X2luc3BlY3Q1KTo6OklOU1BFQ1RfQVVYX1BBU1MKX2F1eF9pbnNwZWN0NShfYXV4X2luc3BlY3Q1KTo6OklOU1BFQ1RfQVVYX1BBU1MgLS0+IHxQVVNILVBVTEx8cG9kNihwb2Q2KTo6OlBPRApwb2Q2KHBvZDYpOjo6UE9EIC0uLT4gfFBVQi1TVUJ8aW5zcGVjdDd7e2luc3BlY3Q3fX06OjpJTlNQRUNUCnBvZDYocG9kNik6OjpQT0QgLS0+IHxQVUItU1VCfF9hdXhfaW5zcGVjdDgoX2F1eF9pbnNwZWN0OCk6OjpJTlNQRUNUX0FVWF9QQVNTCl9hdXhfaW5zcGVjdDgoX2F1eF9pbnNwZWN0OCk6OjpJTlNQRUNUX0FVWF9QQVNTIC0tPiB8UFVTSC1QVUxMfGdhdGhlcl9pbnNwZWN0e3tnYXRoZXJfaW5zcGVjdH19Ojo6Sk9JTl9JTlNQRUNUCmluc3BlY3R7e2luc3BlY3R9fTo6OklOU1BFQ1QgLS4tPiB8UFVTSC1QVUxMfGdhdGhlcl9pbnNwZWN0e3tnYXRoZXJfaW5zcGVjdH19Ojo6Sk9JTl9JTlNQRUNUCmluc3BlY3Q0e3tpbnNwZWN0NH19Ojo6SU5TUEVDVCAtLi0+IHxQVVNILVBVTEx8Z2F0aGVyX2luc3BlY3R7e2dhdGhlcl9pbnNwZWN0fX06OjpKT0lOX0lOU1BFQ1QKaW5zcGVjdDd7e2luc3BlY3Q3fX06OjpJTlNQRUNUIC0uLT4gfFBVU0gtUFVMTHxnYXRoZXJfaW5zcGVjdHt7Z2F0aGVyX2luc3BlY3R9fTo6OkpPSU5fSU5TUEVDVApnYXRoZXJfaW5zcGVjdHt7Z2F0aGVyX2luc3BlY3R9fTo6OkpPSU5fSU5TUEVDVCAtLT4gfFBVU0gtUFVMTHxnYXRld2F5X0VORChnYXRld2F5KTo6OkdBVEVXQVkKY2xhc3NEZWYgUE9EIGZpbGw6IzMyQzhDRCxzdHJva2U6IzAwOTk5OQpjbGFzc0RlZiBJTlNQRUNUIGZpbGw6I2ZmNjY2Nixjb2xvcjojZmZmCmNsYXNzRGVmIEpPSU5fSU5TUEVDVCBmaWxsOiNmZjY2NjYsY29sb3I6I2ZmZgpjbGFzc0RlZiBHQVRFV0FZIGZpbGw6IzZFNzI3OCxjb2xvcjojZmZmCmNsYXNzRGVmIElOU1BFQ1RfQVVYX1BBU1MgZmlsbDojZmZmLGNvbG9yOiMwMDAsc3Ryb2tlLWRhc2hhcnJheTogNSA1CmNsYXNzRGVmIHBlYSBmaWxsOiMwMDk5OTksc3Ryb2tlOiMxRTZFNzM="/>

```python
f = Flow().add(name='p1').inspect(uses='DummyEvaluator1') \
        .add(name='p2', needs='gateway').needs(['p1', 'p2']).inspect(uses='DummyEvaluator2').plot()
```

```python

```

### CODE REVIEW

**Comment by JoanFM** [comment]
adding `eval` also introduces an `aux_inspect` but with valid Peas inside?

**Review by JoanFM — CHANGES_REQUESTED** [review]
I think we need tests for this feature.

**Comment by hanxiao** [comment]
it has tests tests/unit/flow/test_flow_eval_pod.py

**Comment by JoanFM** [comment]
> it has tests tests/unit/flow/test_flow_eval_pod.py

Ah ok, so this is an enforced feature? Why do not we leave this as an optional feature? So that evaluate can end in a different end and it will not block the end of the request?

**Comment by hanxiao** [comment]
> Ah ok, so this is an enforced feature? Why do not we leave this as an optional feature? So that evaluate can end in a different end and it will not block the end of the request?

sure

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
