### PR TITLE
docs(101): added greek translation to 101 chapter

### PR DESCRIPTION
**Pull request by DimitrisPr**
I added a Greek translation to 101 chapter. Also added the Greek menu option to all `README.*.md`
I will also translate the main README.md in Greek this weekend.

### CODE REVIEW

**Comment by nan-wang** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

**Comment by DimitrisPr** [comment]
@nan-wang Changed commit names based on the convention

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by nan-wang** [comment]
recheckcla

**Comment by nan-wang** [comment]
@DimitrisPr Thanks for your great contribution. The very last thing is to sign the CLA as mentioned above.

**Comment by DimitrisPr** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Pull request merged**
