### PR TITLE
refactor: use default cached property

### PR DESCRIPTION
**Pull request by bwanglzu**
WIP on tests

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200526800554871) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by deepankarm** [comment]
`cached_property` usage in JinaD code is not proper & needs refactoring. The change in this PR might have side effects that I would like to avoid right before the release. Is it possible for the JinaD cached_property removal to be postponed?

**Comment by bwanglzu** [comment]
@deepampatel get it

**Comment by deepampatel** [comment]
> @deepampatel get it

Cc @deepankarm @bwanglzu 😉

**Comment by bwanglzu** [comment]
closed because `lru_cache` needs `DocumentArray` to be hashable, while `DocumentArray` is mutable. Better to keep the original implementation.

**Pull request closed without merging**
