### PR TITLE
chore: style helloworld html

### PR DESCRIPTION
**Pull request by alexcg1**
- Bootstrap
- Same logo as repo
- Tweaked English

### CODE REVIEW

**Comment by bhavsarpratik** [comment]
Sadly, I have no idea of HTML

**Comment by JoanFM** [comment]
I do not know, I trust you @alexcg1

**Review by JoanFM — APPROVED** [review]

**Comment by hanxiao** [comment]
@alexcg1 would be good to paste a screenshot of the helloworld page now

**Comment by alexcg1** [comment]
Screenshot from 2020-11-12 12-50-44

**Review by JoanFM — CHANGES_REQUESTED** [review]
It does not show results right?

**Comment by alexcg1** [comment]
Screenshot from 2020-11-12 13-09-46

**Comment by alexcg1** [comment]
Screenshot from 2020-11-12 13-18-11
Old version for reference

**Comment by alexcg1** [comment]
Note: Logo in new version is animated logo from our readme

**Review by JoanFM — APPROVED** [review]

**Comment by hanxiao** [comment]
merge now. frankly i dont see the need of bootstrap in this case. but maybe you are planning more UI touch later?

**Comment by alexcg1** [comment]
> merge now. frankly i dont see the need of bootstrap in this case. extra dependency. but maybe you are planning more UI touch later?

Since this is one of the first things people will use to test Jina to see it's capabilities, let's make it look good to create an even better first impression.

**Pull request merged**
