### PR TITLE
 modified readme korean ver

### PR DESCRIPTION
**Pull request by rabbits99**
We checked someone translated README file for korean already, but we found many errors with this korean file. So we modified some words with our fluent korean based on his readme translation.
This version can be read easily for korean.
Thanks you!!!!!!!!!

### CODE REVIEW

**Comment by JoanFM** [comment]
Hey @rabbits99 , no file change appears in this PR

**Comment by rabbits99** [comment]
I attached new file named "Update README.kr.md" at commits. Can you check it?

**Comment by JoanFM** [comment]
> I attached new file named "Update README.kr.md" at commits. Can you check it?

It says 0 files changed

**Comment by rabbits99** [comment]
Sorry for making confusion
I uploaded again..
Thank you

**Pull request closed without merging**
