### PR TITLE
docs(contributing): fix a broken link

### PR DESCRIPTION
**Pull request by NouiliKh**
In the contributing.md file, there is a broken link that needs to be changed:

image

I will just change which link jina-101 is referring to: from "./101/README.html" to  "https://github.com/jina-ai/jina/tree/master/docs/chapters/101"

### CODE REVIEW

**Comment by JoanFM** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)
#553 :bookmark: Commit Message Guideline for the First Time Contributor
jina-ai/jina | Jun 21st | Added by GitHub
CONTRIBUTING.md
jina-ai/jina | Added by GitHub

**Comment by JoanFM** [comment]
> Bad commit message, please refer to:
> 
> * [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
> * [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)
>   #553 bookmark Commit Message Guideline for the First Time Contributor
>   jina-ai/jina | Jun 21st | Added by GitHub
>   CONTRIBUTING.md
>   jina-ai/jina | Added by GitHub

Hey @NouiliKh ,

It seems that some of your commits do not comply with our guidelines, please change the commit messages as per comment above

**Comment by NouiliKh** [comment]
@JoanFM I am sorry for the number of commits I made for a simple thing. I had issues with changing the name of the commit but I guess the last one is fine.

**Comment by JoanFM** [comment]
> @JoanFM I am sorry for the number of commits I made for a simple thing. I had issues with changing the name of the commit but I guess the last one is fine.

Hey @NickCwh,

the problem is that one bad commit already invalidates the check. You may want to close this PR and reopen a new one?

**Comment by NouiliKh** [comment]
> > @JoanFM I am sorry for the number of commits I made for a simple thing. I had issues with changing the name of the commit but I guess the last one is fine.
> 
> Hey @NickCwh,
> 
> the problem is that one bad commit already invalidates the check. You may want to close this PR and reopen a new one?

@JoanFM That makes sense. I will do that.
btw you tagged the wrong person.

**Pull request closed without merging**
