### PR TITLE
docs(search-input): focus on the search input when "/" is pressed

### PR DESCRIPTION
**Pull request by emmaadesile**
**Describe the feature**
Users will have a better experience using the documentation if they can easily access the search input without using their mouse.

**Your proposal**
I have implemented a feature that adds focus to the search input when a user presses the "/" key.

### CODE REVIEW

**Comment by emmaadesile** [comment]
@JoanFM My PR has 2 failed checks because of the `cla-check`. Please give me more information about how to complete/sign the CLA.

**Comment by JoanFM** [comment]
recheckcla

**Comment by emmaadesile** [comment]
***I have read the CLA Document and I hereby sign the CLA***

**Comment by JoanFM** [comment]
recheckcla

**Comment by hanxiao** [comment]
Thanks for your contribution. Unfortunately, as you didn't set up your local git config correctly, the author of your commit does not match with your Github account. This poses problems:

- Your contribution can not be credited, and will not show up in the list of contributors (as bad git config = anonymous)
- We can not accept CLA for anonymous contribution.

Please note that this does not only affect your contribution to Jina, but also affects *all your contribution* to anything on Github. So better fix it, once for all.

Here is what you can do:
```bash
git config user.name "Correct new name"
git config user.email "correct@new.email" -> match with your Github registered email address
```

Then fix the commit message by
```bash
git commit --amend --author="Author Name <email@address.com>" --no-edit
git push --force
```

**Comment by emmaadesile** [comment]
@hanxiao I have followed the steps to set up my local git config, but it's still failing.

**Comment by emmaadesile** [comment]
recheckcla

**Pull request merged**
