### PR TITLE
refactor(pea): remove unused daemon member

### PR DESCRIPTION
**Pull request by JoanFM**
**Changes introduced**
Remove **daemon** from members of Pea because it is never used.
Do some more cleaning of comments and minor things as I go through the code

### CODE REVIEW

**Comment by hanxiao** [comment]
`self.daemon` is a flag of `multiprocessing` and `threading` library. It is used, implicitly, as `BasePea` is inherited from either `Process` or `Thread`

https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.Process.daemon

> When a process exits, it attempts to terminate all of its daemonic child processes.


If you remove that flag, I'm not sure the process who spawns the pea can later terminate it correctly.

**Comment by JoanFM** [comment]
> `self.daemon` is a flag of `multiprocessing` and `threading` library. It is used, implicitly, as `BasePea` is inherited from either `Process` or `Thread`
> 
> https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.Process.daemon
> 
> > When a process exits, it attempts to terminate all of its daemonic child processes.
> 
> If you remove that flag, I'm not sure the process who spawns the pea can later terminate it correctly.

Where is this inheritance set?

**Comment by JoanFM** [comment]
> the magic happens in
> 
> ```python
> class BasePea(metaclass=PeaMeta):
> ```
> 
> Inside `PeaMeta.__call__`, it reads `args.runtime` and choose the inheritance on the fly

Can we make it more explicit when we pass the **daemon** argument to the Process or Thread?

**Comment by hanxiao** [comment]
Is there a reason `daemon=False`?

**Comment by JoanFM** [comment]
> Is there a reason `daemon=False`?

No, that is exactly what I mean, that having a member that is always the same seems weird, but anyway no big reason to change what is working

**Pull request closed without merging**
