### PR TITLE
fix: pytorch sparse ndarray constructor

### PR DESCRIPTION
**Pull request by bwanglzu**
Was working together with @davidbp on sparse ndarray. We were never been able to set/get value to the `SparseNdarray` with Pytorch backend. Since in the child class we forget to add `proto` to the constructor.

This PR fix bug in the constructor for Pytorch sparse ndarray, without `proto` the getter and setter will always be initialised as `null_proto`.

### CODE REVIEW

**Comment by nan-wang** [comment]
Maybe you can add a test to show the issue

**Comment by bwanglzu** [comment]
@nan-wang no problem, will add now

**Comment by hanxiao** [comment]
wait, if pytorch sparse does not work, then why this test passed all the time? tests/unit/types/ndarray/test_ndarray.py L100 onwards?

**Comment by bwanglzu** [comment]
@hanxiao it's related to our class inherence..normally we get/set value in `NdArray` (`generic.py`), then you'll see the issue.

**Comment by davidbp** [comment]
The issue was not visible from the `NDArray` object but when a `Document` had to interact with it. This solves the issue.

**Review by davidbp — COMMENTED** [review]
Looks good to me

**Review by davidbp — APPROVED** [review]

**Comment by bwanglzu** [comment]
merged this PR since it's blocking #2207

**Pull request merged**
