### PR TITLE
refactor chunkset and matchset append method

### PR DESCRIPTION
**Pull request by bwanglzu**
blocking #1368 .
When refactoring `traverse_apply`, need a lot of chunk level test cases. While `ChunkSet.append` is not working when append document on `Sequence[Document]`. 
image

Why?
`docs_proto` was defined as `Union['RepeatedCompositeContainer', Sequence['Document']]`, the current implementation does not support operations on sequence of documents.

What has been changed?
1. Refactored `MatchSet` and `ChunkSet` , allow `append` operation on a list of document.
2. Add tests.

Didn't add unit test case to initialise a `DocumentSet` or `MatchSet` when `self._docs_proto`  is `RepeatedCompositeContainer`. (I was not able to initialise `RepeatedCompositeContainer` manually, while it has been covered when testing a driver).

### CODE REVIEW

**Comment by JoanFM** [comment]
Why does it exist thr class ChunkSet and is not merged with DocumentSet?

**Comment by bwanglzu** [comment]
@JoanFM as far as know, in `ChunkSet` we overwrite the `append` method in `DocumentSet` to set the `parent_id` and `granularity`.

**Comment by hanxiao** [comment]
> Why does it exist thr class ChunkSet and is not merged with DocumentSet?

ChunkSet and MatchSet are inherited from DocumentSet, I did it on purpose to abstract the logic of `add_chunk` and `add_match`

**Comment by JoanFM** [comment]
Makes sense ! Thanks for clarification

**Review by hanxiao — APPROVED** [review]
👍

**Pull request merged**
