### PR TITLE
fix(transformers): fixed cached_property decorator implementation

### PR DESCRIPTION
**Pull request by rohan1chaudhari**
The `cached_property` decorator was bugged and wasn't retrieving the cached values.

### CODE REVIEW

**Comment by JoanFM** [comment]
Thanks for your contribution. Unfortunately, as you didn't set up your local git config correctly, the author of your commit does not match with your Github account. This poses problems:

Your contribution can not be credited, and will not show up in the list of contributors (as bad git config = anonymous)
We can not accept CLA for anonymous contribution.

Please note that this does not only affect your contribution to Jina, but also affects all your contribution to anything on Github. So better fix it, once for all.

Here is what you can do:

```bash
git config user.name "Correct new name"
git config user.email "correct@new.email" -> match with your Github registered email address
```
Then fix the commit message by
```bash
git commit --amend --author="Author Name <email@address.com>" --no-edit
git push --force
```

**Comment by JoanFM** [comment]
recheckcla

**Comment by JoanFM** [comment]
Could you please add some tests to validate the functionality?

**Comment by rohan1chaudhari** [comment]
> Could you please add some tests to validate the functionality?

Added. Let me know if you need something more.

**Comment by JoanFM** [comment]
> Thanks for your contribution. Unfortunately, as you didn't set up your local git config correctly, the author of your commit does not match with your Github account. This poses problems:
> 
> Your contribution can not be credited, and will not show up in the list of contributors (as bad git config = anonymous)
> We can not accept CLA for anonymous contribution.
> 
> Please note that this does not only affect your contribution to Jina, but also affects all your contribution to anything on Github. So better fix it, once for all.
> 
> Here is what you can do:
> 
> ```shell
> git config user.name "Correct new name"
> git config user.email "correct@new.email" -> match with your Github registered email address
> ```
> 
> Then fix the commit message by
> 
> ```shell
> git commit --amend --author="Author Name <email@address.com>" --no-edit
> git push --force
> ```

Some of your commits were made without the proper github config, please refer to my previous message

**Comment by JoanFM** [comment]
I think you need to update the commit 621983e3d4f151abaa9f05906387dc59e3a7bc69

`Merge pull request #1 from jina-ai/master `

**Pull request closed without merging**
