### PR TITLE
ci(unittest): allow test discovery from unittest

### PR DESCRIPTION
**Pull request by JoanFM**
Changing the CI command to execute unittests.

### CODE REVIEW

**Comment by JoanFM** [comment]
Tests under executors.crafters.audio are failing due to the numba version in the system. librosa requires numba version==0.48 because from 0.50 and up it removes decorators which are needed. It would be important to know if there is another dependency for which we need numba library.

**Comment by JoanFM** [comment]
Test executor.crafter.segmenter fails functionally

**Comment by nan-wang** [comment]
> Tests under executors.crafters.audio are failing due to the numba version in the system. librosa requires numba version==0.48 because from 0.50 and up it removes decorators which are needed. It would be important to know if there is another dependency for which we need numba library.

`librosa` is only used in `executors.crafters.audio`.

**Comment by nan-wang** [comment]
#612 solved in this issue.

**Pull request closed without merging**
