### PR TITLE
fix: encoding

### PR DESCRIPTION
**Pull request by florian-hoenicke**
Currently there are encoding problems when using jina under windows as we can see in this issue:
https://github.com/jina-ai/gptdeploy/issues/49

### CODE REVIEW

**Comment by JoanFM** [comment]
Have you tried doing this?

**Comment by florian-hoenicke** [comment]
@JoanFM Yes, I just tried PYTHONUTF8=1, , but it is also not working

**Comment by JoanFM** [comment]
I am a little concerned if this may cause any trouble for Windows user who write their files on Windows and for whom the encoding would not be this one.

**Comment by florian-hoenicke** [comment]
ASCII is a subset of UTF-8. So those files would be able to open.
With this, we have covered almost all possible cases
What you can do at some point is to detect the encoding
```
import chardet
with open(file_path, 'rb') as file:
    raw_data = file.read()
    encoding = chardet.detect(raw_data)['encoding']
with open(file_path, 'r', encoding=encoding) as file:
    content = file.read()
```

**Comment by florian-hoenicke** [comment]
utf-8 is standard
VS code uses it:
image
Pycharm uses it:
image
Atom uses it:
image
Even python itself promotes utf-8
image

There is no reason we should support something else.

**Review by JoanFM — APPROVED** [review]

**Comment by florian-hoenicke** [comment]
Is it normal that the graceful test takes that long and the ecosystem test is failing? @JoanFM

**Pull request merged**
