### PR TITLE
fix: typo in top k

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Comment by JoanFM** [comment]
@deepankarm may it be the source of your problem?

**Comment by hanxiao** [comment]
this is not a typo

**Comment by hanxiao** [comment]
https://docs.jina.ai/api/jina.drivers.html?highlight=querysetreader#jina.drivers.QuerySetReader

**Comment by hanxiao** [comment]
you use `_` then you lose reading from queryset in the payload, this is how `QuerySetReader` is implemented

**Pull request closed without merging**
