### PR TITLE
fix(logs): info logs input, out, ctrl port

### PR DESCRIPTION
**Pull request by JoanFM**
**Changes introduced**
This log must be helpful for external pods, also it gives less the feeling of a blocked executor

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200537650891463) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by niuzs-alan — APPROVED** [review]
LGTM

**Comment by niuzs-alan** [comment]
Some error happend in the CI.
I read the details, and I don't think the update of log level could cause these errors.
Let me re-run the test firstly.
And maybe we need to do some more research for the automatic CI tasks' schedule.

**Review by hanxiao — CHANGES_REQUESTED** [review]
"ready and listening" msg serves the purpose already

**Comment by JoanFM** [comment]
> "ready and listening" msg serves the purpose already

But if I want to have an external Pod. I may want to have a log to know its input port so that I can configure my other Flows

**Pull request closed without merging**
