### PR TITLE
feat(sandbox): send all arguments to hubble

### PR DESCRIPTION
**Pull request by delgermurun**
Ref https://github.com/jina-ai/hubble/issues/289

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
Which `test` proves that it captures properly the `args` provided in the Deployment?

**Comment by delgermurun** [comment]
@JoanFM 

> Which `test` proves that it captures properly the `args` provided in the Deployment?

Pushed unit test that verifies `args` in the request payload.
But right now, we don't have e2e tests for it.

**Comment by JoanFM** [comment]
> @JoanFM
> 
> > Which `test` proves that it captures properly the `args` provided in the Deployment?
> 
> Pushed unit test that verifies `args` in the request payload. But right now, we don't have e2e tests for it.

Do not need e2e but we can at least try with mocks that the parameters are properly passed

**Comment by delgermurun** [comment]
@JoanFM
> Do not need e2e but we can at least try with mocks that the parameters are properly passed

Added assertion on previous mock test https://github.com/jina-ai/jina/pull/4402/commits/411b60cffa745244c5a9b825c022c0e70e4cfd60

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
