### PR TITLE
fix: pea order pod

### PR DESCRIPTION
**Pull request by florian-hoenicke**

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
Why is this wanted? is it about the closure order?

**Comment by florian-hoenicke** [comment]
> Why is this wanted? is it about the closure order?

Yes closing order and starting order in case of `noblock_on_start = False`.
The head pea should start after all the other peas started.
In the compound pod case, the head pea of a pod will be a dealer at the same time.
Means on startup it will send an idle request to the compound pod head pea. The compound pod head pea might then immediately return a data request.
In case the other peas of the pod are not started, the requests can not be processed.

**Comment by JoanFM** [comment]
> > Why is this wanted? is it about the closure order?
> 
> Yes closing order and starting order in case of `noblock_on_start = False`.
> The head pea should start after all the other peas started.
> In the compound pod case, the head pea of a pod will be a dealer at the same time.
> Means on startup it will send an idle request to the compound pod head pea. The compound pod head pea might then immediately return a data request.
> In case the other peas of the pod are not started, the requests can not be processed.

Are we sure about this? When a Dealer Pea starts, sends the IDLE message to the `router`. In this case it will not be started right?

**Comment by florian-hoenicke** [comment]
@JoanFM I thought this might solve a problem I had with the replicas where some requests were hanging. But it was not the reason.

**Pull request closed without merging**
