### PR TITLE
docs(101): cherry pick content

### PR DESCRIPTION
**Pull request by alexcg1**
I've cherry picked text from my recent (demerged) edits and re-incorporated into 101 from master branch

## I excluded:

* Reformatting/Removing any pics
* What is Jina, Why Neural Search sections
* Reordering content
* Including any questions
* Any extra analogies (would prefer to check analogy accuracy with team before I do that)

## Note

* As you can see from [the updated 101](https://github.com/jina-ai/jina/tree/docs-101/docs/chapters/101), my updated text leads to some text below image for document/chunk which doesn't look great. Should I **cut the text** or **find some way to increase image padding**? (image attached for reference in case its due to my resolution)

Screenshot from 2020-06-19 13-24-12

### CODE REVIEW

**Comment by alexcg1** [comment]
Closes #542 

For the conflicts, shall I resolve those myself? They look pretty straightforward

**Comment by hanxiao** [comment]
bad commit messages.https://github.com/jina-ai/jina/issues/553

**Comment by alexcg1** [comment]
Sorry about that - fixed the capitalization issue now

**Comment by hanxiao** [comment]
still 
image

**Comment by alexcg1** [comment]
I'm trying to find out what's wrong with these commit messages. I even installed [commitlint](https://github.com/conventional-changelog/commitlint) on my local machine and passed each one through - they all passed.

Do we have a non-default commitlint config?

**Comment by alexcg1** [comment]
Great. Looks like removing the semicolons (or some other black magic) solved the commit linting issue

**Comment by alexcg1** [comment]
@hanxiao I think all the commitlint issues are fixed. Not sure why it's not passing unit tests though

**Comment by hanxiao** [comment]
yep sometimes the unittest timeout because of the random "port already in used". This happens randomly and mostly because of the github action instance environment is containerized and jina add another layer of containerization to it. Some resources are not released correctly.

**Pull request merged**
