### PR TITLE
refactor: clean env variable when closing pea

### PR DESCRIPTION
**Pull request by JoanFM**
**Changes introduced**
I have seen weird behavior where it seemed that some process may be recycled (does that make sense)?

### CODE REVIEW

**Review by bhavsarpratik — APPROVED** [review]

**Review by hanxiao — CHANGES_REQUESTED** [review]
let's put this on hold as we clarify the reason. Recycle process is not possible

**Comment by JoanFM** [comment]
image

This is what raised my eyebrow

**Comment by JoanFM** [comment]
> let's put this on hold as we clarify the reason. Recycle process is not possible

I understood it now, We run some tests with backend `thread` and so the `JINA_POD_NAME` gets in the main process, and I guess next test starts flow in the same process and from then on, the logs look quite nasty

**Comment by hanxiao** [comment]
so close this PR?

**Comment by JoanFM** [comment]
i think it shows better logs when testing

**Pull request closed without merging**
