### PR TITLE
fix: cuda round robin

### PR DESCRIPTION
**Pull request by delgermurun**
Goals:

- fix: cuda round robin

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
Please add test

**Comment by alaeddine-13** [comment]
> Please add test

tested now

**Comment by JoanFM** [comment]
> > Please add test
> 
> tested now

Tests are failing

**Comment by hanxiao** [comment]
whis is this fixing?

**Review by hanxiao — CHANGES_REQUESTED** [review]
cant tell why this PR is meaningful, what exactly bug is solving

**Pull request closed without merging**
