### PR TITLE
feat(chatbot): increase the timeout_ready to 600000ms

### PR DESCRIPTION
**Pull request by niuzs-alan**
Default 1 minute(60000ms) `timeout_ready` was not enough to download CSV data in Beijing.
We specify the`timeout_ready`(not default one) to 10 minutes(600000ms) as a increase.

### CODE REVIEW

**Comment by bwanglzu** [comment]
@niuzs-alan pull the latest change on master to your feature branch

**Comment by niuzs-alan** [comment]
> @niuzs-alan pull the latest change on master to your feature branch

Thank you!

**Review by bwanglzu — APPROVED** [review]
LGTM!

**Review by bwanglzu — COMMENTED** [review]
Maybe it's better to pass the variable as an argument in `args`? just like `args.parallel`, and make it default as 600000

**Comment by niuzs-alan** [comment]
> Maybe it's better to pass the variable as an argument in `args`? just like `args.parallel`, and make it default as 600000

Lovely suggestions! 
Let we see more together.

**Comment by nan-wang** [comment]
@niuzs-alan There is `--download-proxy` argument for setting up the proxy. The following cmd can speed up the downloading, given `127.0.0.1:7890` is the local proxy address

```bash
jina hello chatbot --download-proxy 127.0.0.1:7890
```

**Pull request merged**
