### PR TITLE
build: add hub integration

### PR DESCRIPTION
**Pull request by floralatin**
# Context : 

In order to catch errors before the Jina core's release, we need to test Hubble integration on the core's master branch

# What the pr is doing
make some base api sanity check https://github.com/jina-ai/hub-integration

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
Doesn't this generate a very dangerous cross-dependency @mapleeit @nomagick ?

**Comment by mapleeit** [comment]
What do you mean by very dangerous?

**Comment by JoanFM** [comment]
> What do you mean by very dangerous?

that there will be a deadlock between Hub and Jina Core PRs

**Comment by mapleeit** [comment]
We should only add this before release as we discussed before. @floralatin 

Then I guess it's fine since it will be only triggered when releasing? @JoanFM

**Comment by floralatin** [comment]
> We should only add this before release as we discussed before. @floralatin
> 
> Then I guess it's fine since it will be only triggered when releasing? @JoanFM

i see

**Review by mapleeit — CHANGES_REQUESTED** [review]
Remove it in `ci.yml`. Only trigger it before releasing

**Comment by JoanFM** [comment]
Can we then do it in `CD` after merge but not requiring it to have a successfull CD? So that Hub can get the alert but not pollute the CD status?

**Comment by mapleeit** [comment]
> Can we then do it in CD after merge but not requiring it to have a successfull CD? So that Hub can get the alert but not pollute the CD status?

But then we'll need another patch version if things go wrong. The purpose is to make sure that **before releasing**, we know something is wrong and we need to fix something instead of after. 

The same logic comes for Wolf, Jina Now and other products as well.

**Comment by floralatin** [comment]
> Remove it in `ci.yml`. Only trigger it before releasing

yes, i will improve it

**Comment by JoanFM** [comment]
> > Can we then do it in CD after merge but not requiring it to have a successfull CD? So that Hub can get the alert but not pollute the CD status?
> 
> But then we'll need another patch version if things go wrong. The purpose is to make sure that **before releasing**, we know something is wrong and we need to fix something instead of after.
> 
> The same logic comes for Wolf, Jina Now and other products as well.

WOLF and NOW depend on Jina and they treat every Jina version update as a PR where they run their own tests. Having Jina NOW fail is not a reason for Core not to release. For Hub it could be different, but then CD is not the right place to be, and CI should be.

**Comment by mapleeit** [comment]
Fair point. But the test have some limits. It can't be used in PR since we can't install merged code in Hubble in a unmerged PR context. (We can specify a branch or commit for Hubble to use, but for unmerged PR, it's hard)

So right now, the best place is CD. And in Hubble, we also use the same test before releasing.

https://github.com/jina-ai/hubble/blob/master/.github/workflows/deploy-on-tag.yml#L111

**Comment by JoanFM** [comment]
> Fair point. But the test have some limits. It can't be used in PR since we can't install unmerged code in Hubble. (We can specify a branch or commit for Hubble to use, but it's hard to use merged content in a unmerged PR)
> 
> So right now, the best place is CD. And in Hubble, we also use the same test before releasing.
> 
> https://github.com/jina-ai/hubble/blob/master/.github/workflows/deploy-on-tag.yml#L111

but on CD, if we have already released, what is the point?

**Comment by mapleeit** [comment]
By CD, I mean before official release. Should be "Manual Release" in Jina Core?

**Comment by floralatin** [comment]
so now. we only add  this before jina core release? and  we make it have some optional ：blocking and on-blocking ？

**Comment by floralatin** [comment]
so we only add this before jina release ?

**Comment by mapleeit** [comment]
> so we only add this before jina release ?

Yes. I think it should be `force-release.yml`, but @floralatin please make sure it's right place. 

Let's improve whenever it goes not well.

**Comment by floralatin** [comment]
> > so we only add this before jina release ?
> 
> Yes. Joan said it should be `force-release.yml`, but @floralatin please make sure it's right place.
> 
> Let's improve whenever it goes not well.

fine

**Comment by floralatin** [comment]
> Remove it in `ci.yml`. Only trigger it before releasing
done

**Review by mapleeit — APPROVED** [review]
LGTM 

---

before merge. We need to add the `JINA_AUTH_TOKEN` to secrets.

**Comment by floralatin** [comment]
> Can we add description on the PR before we merge ?
> 
> At minima
> 
> * the context of the pr : why we need the PR
> * What the pr is doing

the context of the pr :  In order to catch errors before the Jina core's release, we need to test Hubble integration on the core's master branch 

What the pr is doing:  make some  base api sanity check

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
