### PR TITLE
docs(proto): update proto docstring

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
- [ ] Cannot find usage of JinaRPC.call. Not sure how to write docstrings for this method.

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
I believe these files are autogenerated by protobuf when compiling the .proto file, so I think we should not add docstrings here

**Comment by Yongxuanzhang** [comment]
Oh ok, if so I will close this PR. How about jina_pb2_grpc.py? @JoanFM  I thought we created those classes.

**Comment by JoanFM** [comment]
> Oh ok, if so I will close this PR. How about jina_pb2_grpc.py? @JoanFM I thought we created those classes.

The same, jina_pb2 are autogenerated

**Comment by Yongxuanzhang** [comment]
> > Oh ok, if so I will close this PR. How about jina_pb2_grpc.py? @JoanFM I thought we created those classes.
> 
> The same, jina_pb2 are autogenerated

Got it. Thanks!

**Pull request closed without merging**
