### PR TITLE
fix: naming of peas replicas in logs

### LINKED ISSUE #2363: fix naming of pods and replicas in logs
See tests.unit.peapods.pods.test_compound_pods.test_pod_naming_with_parallel

Pod should be `replica`

### PR DESCRIPTION
**Pull request by properGrammar**
Intended to fix #2363 

This is a 3nd, cleaner try at #2382 and #2418 lol

cc: @cristianmtr  @maximilianwerk  @JoanFM

### CODE REVIEW

**Comment by cristianmtr** [comment]
Hey @properGrammar 

Thanks a lot for persisting! 

However, I tried running some Flows locally and we noticed that the logs are bit worse to read now. However, reducing the "replica" to just "rep" made it much better. Can you adjust your PR to that instead perhaps? Also remember to adjust the tests

**Review by cristianmtr — CHANGES_REQUESTED** [review]
use `rep-` instead of `replica-`

**Comment by properGrammar** [comment]
You're welcome, @cristianmtr ! Thanks for working with me to help me learn how to submit things per Jina's spec.

I've made the change you requested (and agree that it preserves readability) so hopefully it works for you. Cheers.

**Review by cristianmtr — APPROVED** [review]

**Review by niuzs-alan — COMMENTED** [review]
As for the `docker login` error: [Check run here](https://github.com/jina-ai/jina/pull/2508/checks?check_run_id=2742735846), 
@hanxiao @nan-wang @deepankarm cloud you plz give a hand to check the secrets of `docker login`?

- `DOCKERHUB_DEVBOT_USER`
- `DOCKERHUB_DEVBOT_TOKEN`

**Comment by alexcg1** [comment]
@niuzs-alan could you check what's up with the failing Docker test in our CI? Every other test runs fine

**Comment by properGrammar** [comment]
cristianmtr approved these changes 9 hours ago 🎉😊

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by nan-wang** [comment]
`docker-image-test` is due to the fact the secrets are not available for the forks.

> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Review by niuzs-alan — APPROVED** [review]

**Pull request merged**
