### PR TITLE
docs: add docs about common jina practices

### PR DESCRIPTION
**Pull request by JoanFM**
@alexcg1 @hanxiao 

We have a task to add some documentation about `jina best practices` or `patterns`. Here I showcase the schema I want to introduce and the place. Do you think is good way? Is it the right place in the docs to place it? Are we missing some common pattern that might deserve a little explanation for a user to grasp?

It would be good to review the content @hanxiao, @nan-wang, it may not be so accurate?

### CODE REVIEW

**Comment by alexcg1** [comment]
I like the concept and it looks good - kind of like Jina 101 but much deeper. And I dig that you use examples

**Comment by alexcg1** [comment]
@hanxiao Should we do Jina 10X? 20X? (e.g. 102, 201, 202) - I think this is a good concept to treat knowledge as a progression and something users can see is a step by step process. This would be a good match for a "Jina curriculum"

I've got lots of thoughts in this area ;)

**Comment by JoanFM** [comment]
I think it is important also here to decide the good section:

As I see it, it may have impact as how `jina` brands itself. 

If we put a title such as `jina Design Pattern`, we are branding `jina` almost like a `pseudo programming language for search`. And if we go for this, it may make sense to have a dedicated section.

**Comment by alexcg1** [comment]
@JoanFM I like the title `Jina Design Pattern` since `design pattern` is a phrase that comes up in our presentations a lot.

**Comment by lusloher** [comment]
Hi team @JoanFM such good work, exactly what we need, not just a new framework of how to neural search, but also what dominant patterns are to use Jina :) 
I was looking through it and love the build up, I would just suggest a small change in order, that for each pattern, before closely describing it we give an important exaple (e.g. long-text search) right away, so this way people can read instructions with the set example in mind :)

**Comment by theUnkownName** [comment]
Really cool! I like a lot this style of explaining the concept followed by an example, we should try to make more of this.

**Pull request merged**
