### PR TITLE
chore: remove Nan, Max and Joan as codeowners of modules

### PR DESCRIPTION
**Pull request by JoanFM**
@maximilianwerk @nan-wang I can remove you if you want as well

### CODE REVIEW

**Comment by maximilianwerk** [comment]
:+1: please do so.

**Comment by nan-wang** [comment]
I can stay there. :)

**Review by nan-wang — DISMISSED** [review]
LGTM👍

**Comment by nan-wang** [comment]
@JoanFM keep me only for docs, Dockerfiles and resources

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Pull request merged**
