### PR TITLE
Replacing "Cringe translation" in russian version

### PR DESCRIPTION
**Pull request by git-webmaster**

### CODE REVIEW

**Comment by nan-wang** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

**Comment by florian-hoenicke** [comment]
@git-webmaster you can rewrite the commit message using `git rebase -i HEAD~1` and then `reword` your commit to the format mentioned by @nan-wang.

**Comment by git-webmaster** [comment]
I just saw this project on HN, checked README in Russian, and did change wrong translation.
There is no code changed, only text. I can't do nothing more. 
Please, feel free to decline this PR.

**Comment by florian-hoenicke** [comment]
I recreated a pr with the correct commit style. https://github.com/jina-ai/jina/pull/1572
@git-webmaster Thanks for your contribution!

**Pull request closed without merging**
