### PR TITLE
fix(executor): fix sign of condition

### PR DESCRIPTION
**Pull request by guiferviz**
This wrong condition was showing a warning when the values were correct.

### CODE REVIEW

**Comment by nan-wang** [comment]
recheckcla

**Comment by nan-wang** [comment]
@guiferviz hi, there. Thanks for PR. Your contribution is greatly appreciated. Would you please sign the CLA above so that we can proceed to merge this PR?

**Comment by guiferviz** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by guiferviz** [comment]
Thank you @nan-wang, I think it's signed now :)

**Comment by hanxiao** [comment]
recheckcla

**Comment by hanxiao** [comment]
@guiferviz thanks a lot for your contribution ❤️  merge it now

**Pull request merged**
