### PR TITLE
feat(executors): Add numeric crafter - ArrayConverter

### PR DESCRIPTION
**Pull request by phamtrancsek12**
**Issue Link:** This commit does not refer to any issue or feature request

**Description:** In this commit, a numeric crafter is added to allow user to convert raw bytes into a numpy array, which is the input format for numeric encoder.

### CODE REVIEW

**Comment by hanxiao** [comment]
thanks for your contribution ❤️ Could you please elaborate a bit on the potential use case of this crafter?

**Comment by tracy-propertyguru** [comment]
At first I was thinking about if I can index and query the stock prices data (find the stocks that have similar trends). I have tried using `IncrementalPCA` and `cosine` on S&P500 and I think it can be an example for using Jina with time-series data (Although there is other better algorithms to encode stock data, we can add them later) 

StockTrend

However, I didn't see any available crafter for this data format, so I think this crafter can be useful.

**Comment by phamtrancsek12** [comment]
At first I was thinking about if I can index and query the stock prices data (find the stocks that have similar trends). I have tried using `IncrementalPCA` and `cosine` on S&P500 and I think it can be an example for using Jina with time-series data (Although there is other better algorithms to encode stock data, we can add them later) 

StockTrend

However, I didn't see any available crafter for this data format, so I think this crafter can be useful.

**Comment by phamtrancsek12** [comment]
I chose to use `BaseSegmenter` because as I found in the document: `it receives value on the doc-level and returns new value on the chunk-level` (Here, it converts the `raw_bytes` of the doc into a chunk). I also noticed that `BaseSegmenter` is used to create `ImageReader` in `executors/crafters/image/io.py`, it seems like similar concept?

**Comment by nan-wang** [comment]
> * From what you wrote, this is not a `Segmenter` as you didn't segment a doc into chunks. Yours should inherit from a `BaseDocCrafter`. Difference between these crafters can be found in https://docs.jina.ai/api/jina.executors.crafters.html
> * Please use single quote for string everywhere, this is the coding style of this project
> * Please add type hint for your function args

@hanxiao  `BaseDocCrafter` is not what we need in this case, because we don't save arrays at the `Document` level. The role of the `XyzReader` is similar as the `Segmenter`, i.e. read the data (e.g. file path) from the `Document` into the `Chunk` level for further processing. The differences is that `XyzReader` only returns a single `Chunk`. A better solution would be creating a new base class `Reader` for `XyzReader` to avoid confusion.  We can do this in another PR.

**Comment by hanxiao** [comment]
> (Here, it converts the `raw_bytes` of the doc into a chunk). I also noticed that `BaseSegmenter` is used to create `ImageReader` in `executors/crafters/image/io.py`, it seems like similar concept?

hmm, `ImageReader` should also inherit from `BaseDocCrafter` @nan-wang . Please notice that `Segmenter` implement in this way gives you only one single chunk in the document.

**Comment by hanxiao** [comment]
recheckcla

**Comment by tracy-propertyguru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by phamtrancsek12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hanxiao** [comment]
great! looks good to me! merge it and thanks for your contribution ❤️

**Pull request merged**
