### PR TITLE
feat(pod): add device map

### PR DESCRIPTION
**Pull request by xiongma**

### CODE REVIEW

**Comment by xiongma** [comment]
is normal that ci has run for 16 minutes? I cancel it for avoiding extra charging.

**Comment by xiongma** [comment]
@nan-wang

**Comment by xiongma** [comment]
@hanxiao can u take a look at this?

**Comment by JoanFM** [comment]
Hello @xiongma,

Thank you very much for the contribution, it looks realky good! However we are currently undergoing some tests related to GPU usage of the current system and we do not plan to tackle this feature until these actions have been taken. Note that we are covering several different frameworks that can profit from GPUs.

With respect to the github action, do not worry for the costs, plus it has a timeout on its own, you can also hit the restart to execut the CI steps again and see if tests are broken.

**Comment by xiongma** [comment]
@JoanFM when I restart the ci, it appeared this error
`docker.errors.BuildError: manifest for jinaai/jina:test-pip not found`
I searched for this image in the docker hub,  the search result is empty. is this image doesn't exist in the docker hub?

**Comment by xiongma** [comment]
@JoanFM 
if keep this pr in there, this is the error when I restarted the CI.
`docker.errors.BuildError: manifest for jinaai/jina:test-pip not found`
I searched for this image in the docker hub,  the search result is empty. is this image doesn't exist in the docker hub?

**Comment by JoanFM** [comment]
> @JoanFM
> if keep this pr in there, this is the error when I restarted the CI.
> `docker.errors.BuildError: manifest for jinaai/jina:test-pip not found`
> I searched for this image in the docker hub, the search result is empty. is this image doesn't exist in the docker hub?

This is an image generated during `CI` to be used during the CI process. Nor sure what can have gone wrong

**Comment by xiongma** [comment]
> > @JoanFM
> > if keep this pr in there, this is the error when I restarted the CI.
> > `docker.errors.BuildError: manifest for jinaai/jina:test-pip not found`
> > I searched for this image in the docker hub, the search result is empty. is this image doesn't exist in the docker hub?
> 
> This is an image generated during `CI` to be used during the CI process. Nor sure what can have gone wrong

sorry about that, this error just appeared in my local unit test. I thought this image is under jinaai in docker hub.

**Comment by JoanFM** [comment]
> so, should I close this pr? or just keep it in there

I think there is no need to close this PR, since it seems really good, but just do not expect it to be merged in the very short term

**Comment by xiongma** [comment]
ok.

**Comment by JoanFM** [comment]
> > > @JoanFM
> > > if keep this pr in there, this is the error when I restarted the CI.
> > > `docker.errors.BuildError: manifest for jinaai/jina:test-pip not found`
> > > I searched for this image in the docker hub, the search result is empty. is this image doesn't exist in the docker hub?
> > 
> > 
> > This is an image generated during `CI` to be used during the CI process. Nor sure what can have gone wrong
> 
> sorry about that, this error just appeared in my local unit test. I thought this image is under jinaai in docker hub.

Ok, if you want to test locally replicating the exact `CI` process u need to build a jina image and tag it as `jinaai/jina:test-pip`

**Comment by xiongma** [comment]
ok

**Comment by hanxiao** [comment]
the device is is implemented in the wrong place, one should always be careful when touching load_config

**Comment by xiongma** [comment]
you mean the device id in `metas` can be this [1, 2, 3] or just a device number?

**Pull request closed without merging**
