### PR TITLE
fix(hubble): disk cache compatible across python versions

### PR DESCRIPTION
**Pull request by numb3r3**

### CODE REVIEW

**Review by maximilianwerk — CHANGES_REQUESTED** [review]
Can we add some test? Perhaps prepare a pickle file in each python version and check if they are readable in all python versions?

**Comment by numb3r3** [comment]
> Can we add some test? Perhaps prepare a pickle file in each python version and check if they are readable in all python versions?

In this PR, I just clean the cache file when it cannot be loaded correctly.

**Comment by hanxiao** [comment]
@alaeddine-13

**Review by maximilianwerk — APPROVED** [review]
LGTM

**Pull request merged**
