### PR TITLE
feat(http): disable healthcheck access logs with env

### PR DESCRIPTION
**Pull request by deepankarm**
Goals:

- ...
- ...
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/CONTRIBUTING.md#documentation-guidelines) and ask the team.

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
We need to add some documentation about this

**Comment by deepankarm** [comment]
> We need to add some documentation about this

Where should it be added? I don't see a section for health check.

**Review by JoanFM — COMMENTED** [review]
Add this environment variable to the list of environment variables, and then we will document in the ticket about documenting env vars

**Comment by JoanFM** [comment]
@deepankarm once the env var is added to the list in `jina/__init__.py` this env var can be considered in #4823

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
