### PR TITLE
refactor(peapods): restructure code base

### PR DESCRIPTION
**Pull request by hanxiao**
This PR changes `jina/peapods` file structure into:

```
|-peapods
 | |-peas
 | | |-__init__.py
 | | |-headtail
 | | | |-tail.py
 | | | |-__init__.py
 | | | |-head.py
 | | |-container
 | | | |-__init__.py
 | | |-gateway
 | | | |-grpc
 | | | | |-__init__.py
 | | | | |-async_servicer.py
 | | | | |-helper.py
 | | | | |-async_stub.py
 | | | |-rest.py
 | | | |-__init__.py
 | | |-remote
 | | | |-__init__.py
 | | | |-jinad.py
 | | | |-ssh.py
 | |-__init__.py
 | |-pods
 | | |-gateway.py
 | | |-remote.py
 | | |-__init__.py
 | | |-flow.py
 | | |-helper.py
 | | |-mutable.py
 | |-zmq
 | | |-__init__.py
```

### CODE REVIEW

**Review by JoanFM — DISMISSED** [review]

**Review by deepankarm — COMMENTED** [review]
We have a mix of absolute vs relative imports in many places.

**Comment by deepankarm** [comment]
```
 |-pods
 | | |-flow_pod.py
 | | |-__init__.py
 | | |-mutable_pod.py
 | | |-remote_pod.py
 | | |-helper.py
 | | |-gateway_pod.py
```
We can avoid recursive naming.

**Comment by hanxiao** [comment]
> ```
>  |-pods
>  | | |-flow_pod.py
>  | | |-__init__.py
>  | | |-mutable_pod.py
>  | | |-remote_pod.py
>  | | |-helper.py
>  | | |-gateway_pod.py
> ```
> 
> We can avoid recursive naming.

removing `_pod` or `_pea` suffix under `pods/` or `peas/` ?  what do you think? @JoanFM

**Comment by JoanFM** [comment]
> > ```
> >  |-pods
> >  | | |-flow_pod.py
> >  | | |-__init__.py
> >  | | |-mutable_pod.py
> >  | | |-remote_pod.py
> >  | | |-helper.py
> >  | | |-gateway_pod.py
> > ```
> > 
> > 
> > We can avoid recursive naming.
> 
> removing `_pod` or `_pea` filename suffix under `pods/` or `peas/` ? what do you think? @JoanFM

Good for me as long as it is as much consistent as possible

**Pull request merged**
