### PR TITLE
feat(types): allow scipy metric in match and add minmax normalization

### PR DESCRIPTION
**Pull request by hanxiao**
improve `.match` by
- allowing scipy metric
- allowing 2-arity function
- allowing min-max normalization

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
why did we remove the option to have similarity?

**Comment by hanxiao** [comment]
it is changed min-max normalization for better generalbility and professionality

**Review by davidbp — APPROVED** [review]
LGTM. Note that this changes the default behaviour. Previously all returned results were "higher the better" by default. Now it depends on the metric the user chooses (which is fine for me).
- One question arises: How is the ordering taking into account if larger values are better or lower values?

**Comment by JoanFM** [comment]
> it is changed to min-max normalization for better generalbility and professionality

normalization does not change the meaning of the score to similarity.

**Comment by davidbp** [comment]
My only concern is the updated `top_k` that returns negative values
```
    if descending:
        values = -values
```

**Comment by hanxiao** [comment]
> My only concern is the updated `top_k` that returns negative values
> 
> ```
>     if descending:
>         values = -values
> ```

plz read the full code

**Comment by hanxiao** [comment]
> > it is changed to min-max normalization for better generalbility and professionality
> 
> normalization does not change the meaning of the score to similarity.

https://github.com/jina-ai/jina/pull/3019/files#diff-0f9b5cdc7560c5f53ae28daa201efd41371ff58e80340df23991ad2d27bb9f84R42

**Pull request merged**
