### PR TITLE
feat(helloworld): add cli arg 'download-proxy'

### PR DESCRIPTION
**Pull request by Morriaty-The-Murderer**
The story began with a guy who ran the hello-world demo failed in the first three days. Support to those ones who are struggling to the unfriendly network.

### CODE REVIEW

**Comment by hanxiao** [comment]
Nicely done! Thanks for your contribution. ❤️  Unfortunately, as you didn't set up your local git config correctly, the author of your commit does not match with your Github account. This poses problems:

- Your contribution can not be credited, and will not show up in the list of contributors (as bad git config = anonymous)
- We can not accept CLA for anonymous contribution.

image

**Comment by hanxiao** [comment]
Please note that this does not only affect your contribution to Jina, but also affects *all your contribution* to anything on Github. So better fix it, once for all.

Here is what you can do:
```bash
git config user.name "Correct new name"
git config user.email "correct@new.email" -> match with your Github registered email address
```

Then fix the commit message by
```bash
git commit --amend --author="Author Name <email@address.com>" --no-edit
git push --force
```

**Comment by hanxiao** [comment]
recheckcla

**Comment by hanxiao** [comment]
recheckcla

**Comment by Morriaty-The-Murderer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
