### PR TITLE
fix: broken link to extra deps documentation

### PR DESCRIPTION
**Pull request by akanz1**

### CODE REVIEW

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by nan-wang** [comment]
recheckcla

**Comment by akanz1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bwanglzu** [comment]
@akanz1 can you merge the latest master branch into your feature branch to pass the docstring check?

**Comment by akanz1** [comment]
@bwanglzu done, seems to pass now

**Pull request merged**
