### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by usmudit**

### CODE REVIEW

**Comment by beertocode** [comment]
Please assign me this issue.

**Review by JoanFM — CHANGES_REQUESTED** [review]
Could you @alexcg1 review if this is something we want in our Readme? It seems a little hacktoberfesty?

**Comment by JoanFM** [comment]
> Please assign me this issue.

Hello @beertocode ,

Be aware that this is not an issue but a PR open from the community. So no work to be assigned other than reviewing it.

**Comment by alexcg1** [comment]
> Could you @alexcg1 review if this is something we want in our Readme? It seems a little hacktoberfesty?

Agreed. This isn't really that useful. And you know how picky we are about our README ;)

**Pull request closed without merging**
