### PR TITLE
fix(docs): code can't be picked up fluently

### PR DESCRIPTION
**Pull request by JamesTang-jinaai**
Added a function to minimize and maximize the Table of Contents, and canceled the scroll bar on the code in Edge Browser.
Issue Link: https://github.com/jina-ai/jina/issues/772

Screenshot: init page
screenshot1
Screenshot: minimize Table of Contents
screenshot2

### CODE REVIEW

**Comment by hanxiao** [comment]
can you take a screenshot of the effect now? Modify your PR body and paste the image

btw, your commit message is probably too long. 

Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

**Comment by JamesTang-jinaai** [comment]
> can you take a screenshot of the effect now? Modify your PR body and paste the image
> 
> btw, your commit message is probably too long.
> 
> Bad commit message, please refer to:
> 
> * [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
> * [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

the comment problem seems complex, I'm sorry for the inconvinent. Shall I commit the code again?

**Comment by hanxiao** [comment]
Use `git commit --amend` and then `git push force` to fix it.

**Comment by JamesTang-jinaai** [comment]
I've tried yesterday, but I encountered some clash, I'm going to open a new PR istead.

**Pull request closed without merging**
