### PR TITLE
fix: avoid the bounding RouteDriver to the ControlRequest

### LINKED ISSUE #1067: RouteDriver can't be used independently
**Describe the bug**
The `RouteDriver` is bounded to `ControlReqRequest`. Currently, change the `executors._route.yml` to the following will break the flow. 

```
!BaseExecutor
with: {}
metas:
  name: route
requests:
  on:
    IndexRequest:
      - !RouteDriver {}
    ControlRequest:
      - !RouteDriver {}
    SearchRequest:
      - !RouteDriver {}
```

**Describe how you solve it**

---

**Environment**

**Screenshots**

### PR DESCRIPTION
**Pull request by nan-wang**
resolved #1067 

Currently, only a unit test is added to illustrate the issue.

### CODE REVIEW

**Review by rutujasurve94 — APPROVED** [review]

**Review by hanxiao — CHANGES_REQUESTED** [review]
i don't get the purpose of this PR

**Comment by hanxiao** [comment]
can you tell me what exactly do you want to achieve here?
```
    f = (Flow()
         .add(uses='_forward',
              uses_before=os.path.join(cur_dir, 'yaml', 'route.yml'),
              shards=2))
```

why use `route.yml` instead of `jina pod --help`

```
  --polling {ANY, ALL, ALL_ASYNC}
                        ANY: only one (whoever is idle) replica polls the
                        message; ALL: all workers poll the message (like a
                        broadcast) (choose from: {ANY, ALL, ALL_ASYNC};
                        default: ANY)
  --scheduling {LOAD_BALANCE, ROUND_ROBIN}
                        the strategy of scheduling workload among peas
                        (choose from: {LOAD_BALANCE, ROUND_ROBIN}; default:
                        LOAD_BALANCE)
```

**Comment by hanxiao** [comment]
This PR is depreciated as https://github.com/jina-ai/jina/pull/1070/files#diff-5f6f8d78a4df7070bef9c3566d1b82f7

**Comment by hanxiao** [comment]
Note that the issue is not due to: "avoid the bounding RouteDriver to the ControlRequest". 

The issue is about using weak reference somehow works and fail without it. To elaborate, check `tests/unit/executors/test_route_exec.py`

```python
def test_load_driver():
    b = BaseExecutor.load_config(os.path.join(cur_dir, 'yaml/route.yml'))
    print(b._drivers)

    c = BaseExecutor.load_config('_route')
    assert len(b._drivers['ControlRequest']) == len(c._drivers['ControlRequest'])
    print(c._drivers)
```

gives `b._drivers`
```
{'ControlRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c4d0>,
                    <jina.drivers.control.ControlReqDriver object at 0x10e85c510>],
 'IndexRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c590>],
 'SearchRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c550>],
 'TrainRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c610>]}
```

and `c._drivers`

```
{'ControlRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>,
                    <jina.drivers.control.ControlReqDriver object at 0x10e85c5d0>],
 'IndexRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>],
 'SearchRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>],
 'TrainRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>]}
```

The combinations are the same, but note that in `b._drives` `RouteDriver` are four *different* objects (look at their memory ref), whereas in `c._drivers` `RouteDriver` the same object!

Note, it is easy to understand why `b` gives four and `c` gives one: it is in YAML deserialization and it is **reasonable and expected**.

What I don't understand is why `c` works but `b` not

**Pull request closed without merging**
