### PR TITLE
perf(types): remove warning logic in binary doc construction

### PR DESCRIPTION
**Pull request by hanxiao**
background: https://github.com/jina-ai/jina/pull/3193#pullrequestreview-731999252

close #3193 

```
➜  jina git:(master) ✗ python toy39.py
get embedding ...	get embedding takes 4 seconds (4.49s)

➜  jina git:(perf-rm-warn-logic) ✗ python toy39.py
get embedding ...	get embedding takes 3 seconds (3.99s)
```

### CODE REVIEW

**Review by davidbp — DISMISSED** [review]
LGTM

**Review by JoanFM — COMMENTED** [review]
I guess some imports may be good to remove

**Review by JoanFM — APPROVED** [review]

**Comment by alaeddine-13** [comment]
@hanxiao let me check how this changes affects detecting corrupted documents/dam before merging

**Comment by alaeddine-13** [comment]
> @hanxiao let me check how these changes affects detecting corrupted documents/dam before merging

looks fine

**Pull request merged**
