### PR TITLE
refactor(drivers): remove publishdriver

### PR DESCRIPTION
**Pull request by JoanFM**
**Changes introduced**
I can't find where **PublishDriver** is used, if I am right and is not used, let's remove it

### CODE REVIEW

**Comment by hanxiao** [comment]
yep, it is legacy code. not used anymore.

btw, let's limit our changes on the driver part until #652 is merged.

**Comment by JoanFM** [comment]
> yep, it is legacy code. not used anymore.
> 
> btw, let's limit our changes on the driver part until #652 is merged.

Yes, I am limiting my work related to drivers or involving hard dependencies on proto drivers until it is merged

**Comment by JoanFM** [comment]
@hanxiao did u allow the bot to write the codecov Report? conversation has not been blocked?

**Comment by hanxiao** [comment]
not sure what's happening. but seems all new PR after #658 will be fine?

**Comment by JoanFM** [comment]
now conversation is locked, so still good!

**Pull request merged**
